/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import up.god.jooq.DbHtl;
import up.god.jooq.Indexes;
import up.god.jooq.Keys;
import up.god.jooq.tables.records.ResContractRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResContract extends TableImpl<ResContractRecord> {

    private static final long serialVersionUID = 1158694262;

    /**
     * The reference instance of <code>DB_HTL.RES_CONTRACT</code>
     */
    public static final ResContract RES_CONTRACT = new ResContract();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResContractRecord> getRecordType() {
        return ResContractRecord.class;
    }

    /**
     * The column <code>DB_HTL.RES_CONTRACT.PK_ID</code>. uniqueId,PK_ID
     */
    public final TableField<ResContractRecord, Long> PK_ID = createField("PK_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "uniqueId,PK_ID");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.D_RUNUP_LIMIT</code>. 挂账限制,runupLimit,D_RUNUP_LIMIT
     */
    public final TableField<ResContractRecord, BigDecimal> D_RUNUP_LIMIT = createField("D_RUNUP_LIMIT", org.jooq.impl.SQLDataType.DECIMAL(10, 2), this, "挂账限制,runupLimit,D_RUNUP_LIMIT");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.S_NAME</code>. name,S_NAME
     */
    public final TableField<ResContractRecord, String> S_NAME = createField("S_NAME", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "name,S_NAME");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.S_CODE</code>. code,S_CODE
     */
    public final TableField<ResContractRecord, String> S_CODE = createField("S_CODE", org.jooq.impl.SQLDataType.VARCHAR(36), this, "code,S_CODE");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.S_OPTOR_MOBILE</code>. operatorMobile,S_OPTOR_MOBILE
     */
    public final TableField<ResContractRecord, String> S_OPTOR_MOBILE = createField("S_OPTOR_MOBILE", org.jooq.impl.SQLDataType.VARCHAR(20), this, "operatorMobile,S_OPTOR_MOBILE");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.S_OPTOR_NAME</code>. operatorName,S_OPTOR_NAME
     */
    public final TableField<ResContractRecord, String> S_OPTOR_NAME = createField("S_OPTOR_NAME", org.jooq.impl.SQLDataType.VARCHAR(32), this, "operatorName,S_OPTOR_NAME");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.S_PHONE</code>. phone,S_PHONE
     */
    public final TableField<ResContractRecord, String> S_PHONE = createField("S_PHONE", org.jooq.impl.SQLDataType.VARCHAR(20), this, "phone,S_PHONE");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.J_CONFIG</code>. config,J_CONFIG
     */
    public final TableField<ResContractRecord, String> J_CONFIG = createField("J_CONFIG", org.jooq.impl.SQLDataType.CLOB, this, "config,J_CONFIG");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.RLT_CONTRACT_ITEM</code>. contractItem,RLT_CONTRACT_ITEM
     */
    public final TableField<ResContractRecord, Long> RLT_CONTRACT_ITEM = createField("RLT_CONTRACT_ITEM", org.jooq.impl.SQLDataType.BIGINT, this, "contractItem,RLT_CONTRACT_ITEM");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.RLT_CONTRACT_TYPE</code>. type,RLT_CONTRACT_TYPE
     */
    public final TableField<ResContractRecord, Long> RLT_CONTRACT_TYPE = createField("RLT_CONTRACT_TYPE", org.jooq.impl.SQLDataType.BIGINT, this, "type,RLT_CONTRACT_TYPE");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.R_COMPANY_ID</code>. companyId,R_COMPANY_ID
     */
    public final TableField<ResContractRecord, Long> R_COMPANY_ID = createField("R_COMPANY_ID", org.jooq.impl.SQLDataType.BIGINT, this, "companyId,R_COMPANY_ID");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.R_OPERATOR_ID</code>. operatorId,R_OPERATOR_ID
     */
    public final TableField<ResContractRecord, String> R_OPERATOR_ID = createField("R_OPERATOR_ID", org.jooq.impl.SQLDataType.VARCHAR(36), this, "operatorId,R_OPERATOR_ID");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.IS_RUNUP</code>. runup,IS_RUNUP
     */
    public final TableField<ResContractRecord, Boolean> IS_RUNUP = createField("IS_RUNUP", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "runup,IS_RUNUP");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    public final TableField<ResContractRecord, Boolean> IS_ACTIVE = createField("IS_ACTIVE", org.jooq.impl.SQLDataType.BOOLEAN, this, "active,IS_ACTIVE");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    public final TableField<ResContractRecord, String> Z_SIGMA = createField("Z_SIGMA", org.jooq.impl.SQLDataType.VARCHAR(32), this, "sigma,Z_SIGMA");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.Z_LANGUAGE</code>. language,Z_LANGUAGE
     */
    public final TableField<ResContractRecord, String> Z_LANGUAGE = createField("Z_LANGUAGE", org.jooq.impl.SQLDataType.VARCHAR(8), this, "language,Z_LANGUAGE");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.Z_CREATE_BY</code>. createBy,Z_CREATE_BY
     */
    public final TableField<ResContractRecord, String> Z_CREATE_BY = createField("Z_CREATE_BY", org.jooq.impl.SQLDataType.VARCHAR(36), this, "createBy,Z_CREATE_BY");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.Z_CREATE_TIME</code>. createTime,Z_CREATE_TIME
     */
    public final TableField<ResContractRecord, LocalDateTime> Z_CREATE_TIME = createField("Z_CREATE_TIME", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "createTime,Z_CREATE_TIME");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.Z_UPDATE_BY</code>. updateBy,Z_UPDATE_BY
     */
    public final TableField<ResContractRecord, String> Z_UPDATE_BY = createField("Z_UPDATE_BY", org.jooq.impl.SQLDataType.VARCHAR(36), this, "updateBy,Z_UPDATE_BY");

    /**
     * The column <code>DB_HTL.RES_CONTRACT.Z_UPDATE_TIME</code>. updateTime,Z_UPDATE_TIME
     */
    public final TableField<ResContractRecord, LocalDateTime> Z_UPDATE_TIME = createField("Z_UPDATE_TIME", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "updateTime,Z_UPDATE_TIME");

    /**
     * Create a <code>DB_HTL.RES_CONTRACT</code> table reference
     */
    public ResContract() {
        this(DSL.name("RES_CONTRACT"), null);
    }

    /**
     * Create an aliased <code>DB_HTL.RES_CONTRACT</code> table reference
     */
    public ResContract(String alias) {
        this(DSL.name(alias), RES_CONTRACT);
    }

    /**
     * Create an aliased <code>DB_HTL.RES_CONTRACT</code> table reference
     */
    public ResContract(Name alias) {
        this(alias, RES_CONTRACT);
    }

    private ResContract(Name alias, Table<ResContractRecord> aliased) {
        this(alias, aliased, null);
    }

    private ResContract(Name alias, Table<ResContractRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbHtl.DB_HTL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RES_CONTRACT_FK_RES_CONTRACT_R_COMPANY_ID, Indexes.RES_CONTRACT_FK_RES_CONTRACT_R_OPERATOR_ID, Indexes.RES_CONTRACT_PRIMARY, Indexes.RES_CONTRACT_UK_RES_CONTRACT_S_CODE_Z_SIGMA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ResContractRecord, Long> getIdentity() {
        return Keys.IDENTITY_RES_CONTRACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ResContractRecord> getPrimaryKey() {
        return Keys.KEY_RES_CONTRACT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ResContractRecord>> getKeys() {
        return Arrays.<UniqueKey<ResContractRecord>>asList(Keys.KEY_RES_CONTRACT_PRIMARY, Keys.KEY_RES_CONTRACT_UK_RES_CONTRACT_S_CODE_Z_SIGMA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResContract as(String alias) {
        return new ResContract(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResContract as(Name alias) {
        return new ResContract(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResContract rename(String name) {
        return new ResContract(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResContract rename(Name name) {
        return new ResContract(name, null);
    }
}
