/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import up.god.jooq.DbHtl;
import up.god.jooq.Indexes;
import up.god.jooq.Keys;
import up.god.jooq.tables.records.ResRelCompanyPartnerRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResRelCompanyPartner extends TableImpl<ResRelCompanyPartnerRecord> {

    private static final long serialVersionUID = 865877265;

    /**
     * The reference instance of <code>DB_HTL.RES_REL_COMPANY_PARTNER</code>
     */
    public static final ResRelCompanyPartner RES_REL_COMPANY_PARTNER = new ResRelCompanyPartner();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResRelCompanyPartnerRecord> getRecordType() {
        return ResRelCompanyPartnerRecord.class;
    }

    /**
     * The column <code>DB_HTL.RES_REL_COMPANY_PARTNER.R_COMPANY_ID</code>. companyId,R_COMPANY_ID
     */
    public final TableField<ResRelCompanyPartnerRecord, Long> R_COMPANY_ID = createField("R_COMPANY_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "companyId,R_COMPANY_ID");

    /**
     * The column <code>DB_HTL.RES_REL_COMPANY_PARTNER.R_PARTNER_ID</code>. partnerId,R_PARTNER_ID
     */
    public final TableField<ResRelCompanyPartnerRecord, Long> R_PARTNER_ID = createField("R_PARTNER_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "partnerId,R_PARTNER_ID");

    /**
     * Create a <code>DB_HTL.RES_REL_COMPANY_PARTNER</code> table reference
     */
    public ResRelCompanyPartner() {
        this(DSL.name("RES_REL_COMPANY_PARTNER"), null);
    }

    /**
     * Create an aliased <code>DB_HTL.RES_REL_COMPANY_PARTNER</code> table reference
     */
    public ResRelCompanyPartner(String alias) {
        this(DSL.name(alias), RES_REL_COMPANY_PARTNER);
    }

    /**
     * Create an aliased <code>DB_HTL.RES_REL_COMPANY_PARTNER</code> table reference
     */
    public ResRelCompanyPartner(Name alias) {
        this(alias, RES_REL_COMPANY_PARTNER);
    }

    private ResRelCompanyPartner(Name alias, Table<ResRelCompanyPartnerRecord> aliased) {
        this(alias, aliased, null);
    }

    private ResRelCompanyPartner(Name alias, Table<ResRelCompanyPartnerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbHtl.DB_HTL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RES_REL_COMPANY_PARTNER_FK_RES_REL_CP_PARTNER, Indexes.RES_REL_COMPANY_PARTNER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ResRelCompanyPartnerRecord> getPrimaryKey() {
        return Keys.KEY_RES_REL_COMPANY_PARTNER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ResRelCompanyPartnerRecord>> getKeys() {
        return Arrays.<UniqueKey<ResRelCompanyPartnerRecord>>asList(Keys.KEY_RES_REL_COMPANY_PARTNER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResRelCompanyPartner as(String alias) {
        return new ResRelCompanyPartner(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResRelCompanyPartner as(Name alias) {
        return new ResRelCompanyPartner(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResRelCompanyPartner rename(String name) {
        return new ResRelCompanyPartner(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResRelCompanyPartner rename(Name name) {
        return new ResRelCompanyPartner(name, null);
    }
}
