/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import up.god.jooq.DbHtl;
import up.god.jooq.Indexes;
import up.god.jooq.Keys;
import up.god.jooq.tables.records.SecPermissionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecPermission extends TableImpl<SecPermissionRecord> {

    private static final long serialVersionUID = 394618530;

    /**
     * The reference instance of <code>DB_HTL.SEC_PERMISSION</code>
     */
    public static final SecPermission SEC_PERMISSION = new SecPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecPermissionRecord> getRecordType() {
        return SecPermissionRecord.class;
    }

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.PK_ID</code>. uniqueId,PK_ID
     */
    public final TableField<SecPermissionRecord, String> PK_ID = createField("PK_ID", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "uniqueId,PK_ID");

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.S_NAME</code>. name,S_NAME
     */
    public final TableField<SecPermissionRecord, String> S_NAME = createField("S_NAME", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "name,S_NAME");

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.S_CODE</code>. code,S_CODE
     */
    public final TableField<SecPermissionRecord, String> S_CODE = createField("S_CODE", org.jooq.impl.SQLDataType.VARCHAR(36), this, "code,S_CODE");

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.J_CONFIG</code>. config,J_CONFIG
     */
    public final TableField<SecPermissionRecord, String> J_CONFIG = createField("J_CONFIG", org.jooq.impl.SQLDataType.CLOB, this, "config,J_CONFIG");

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.H_CAT_ID</code>. category,H_CAT_ID
     */
    public final TableField<SecPermissionRecord, Long> H_CAT_ID = createField("H_CAT_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "category,H_CAT_ID");

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.IS_INHERIT</code>. inherit,IS_INHERIT
     */
    public final TableField<SecPermissionRecord, Boolean> IS_INHERIT = createField("IS_INHERIT", org.jooq.impl.SQLDataType.BOOLEAN, this, "inherit,IS_INHERIT");

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    public final TableField<SecPermissionRecord, Boolean> IS_ACTIVE = createField("IS_ACTIVE", org.jooq.impl.SQLDataType.BOOLEAN, this, "active,IS_ACTIVE");

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    public final TableField<SecPermissionRecord, String> Z_SIGMA = createField("Z_SIGMA", org.jooq.impl.SQLDataType.VARCHAR(32), this, "sigma,Z_SIGMA");

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.Z_LANGUAGE</code>. language,Z_LANGUAGE
     */
    public final TableField<SecPermissionRecord, String> Z_LANGUAGE = createField("Z_LANGUAGE", org.jooq.impl.SQLDataType.VARCHAR(8), this, "language,Z_LANGUAGE");

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.Z_CREATE_BY</code>. createBy,Z_CREATE_BY
     */
    public final TableField<SecPermissionRecord, String> Z_CREATE_BY = createField("Z_CREATE_BY", org.jooq.impl.SQLDataType.VARCHAR(36), this, "createBy,Z_CREATE_BY");

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.Z_CREATE_TIME</code>. createTime,Z_CREATE_TIME
     */
    public final TableField<SecPermissionRecord, LocalDateTime> Z_CREATE_TIME = createField("Z_CREATE_TIME", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "createTime,Z_CREATE_TIME");

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.Z_UPDATE_BY</code>. updateBy,Z_UPDATE_BY
     */
    public final TableField<SecPermissionRecord, String> Z_UPDATE_BY = createField("Z_UPDATE_BY", org.jooq.impl.SQLDataType.VARCHAR(36), this, "updateBy,Z_UPDATE_BY");

    /**
     * The column <code>DB_HTL.SEC_PERMISSION.Z_UPDATE_TIME</code>. updateTime,Z_UPDATE_TIME
     */
    public final TableField<SecPermissionRecord, LocalDateTime> Z_UPDATE_TIME = createField("Z_UPDATE_TIME", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "updateTime,Z_UPDATE_TIME");

    /**
     * Create a <code>DB_HTL.SEC_PERMISSION</code> table reference
     */
    public SecPermission() {
        this(DSL.name("SEC_PERMISSION"), null);
    }

    /**
     * Create an aliased <code>DB_HTL.SEC_PERMISSION</code> table reference
     */
    public SecPermission(String alias) {
        this(DSL.name(alias), SEC_PERMISSION);
    }

    /**
     * Create an aliased <code>DB_HTL.SEC_PERMISSION</code> table reference
     */
    public SecPermission(Name alias) {
        this(alias, SEC_PERMISSION);
    }

    private SecPermission(Name alias, Table<SecPermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private SecPermission(Name alias, Table<SecPermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbHtl.DB_HTL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SEC_PERMISSION_PRIMARY, Indexes.SEC_PERMISSION_UK_SEC_PERMISSION_S_CODE_Z_SIGMA, Indexes.SEC_PERMISSION_UK_SEC_PERMISSION_S_NAME_Z_SIGMA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SecPermissionRecord> getPrimaryKey() {
        return Keys.KEY_SEC_PERMISSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SecPermissionRecord>> getKeys() {
        return Arrays.<UniqueKey<SecPermissionRecord>>asList(Keys.KEY_SEC_PERMISSION_PRIMARY, Keys.KEY_SEC_PERMISSION_UK_SEC_PERMISSION_S_NAME_Z_SIGMA, Keys.KEY_SEC_PERMISSION_UK_SEC_PERMISSION_S_CODE_Z_SIGMA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecPermission as(String alias) {
        return new SecPermission(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecPermission as(Name alias) {
        return new SecPermission(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecPermission rename(String name) {
        return new SecPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecPermission rename(Name name) {
        return new SecPermission(name, null);
    }
}
