/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import up.god.jooq.DbHtl;
import up.god.jooq.Indexes;
import up.god.jooq.Keys;
import up.god.jooq.tables.records.SecRelRolePermRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecRelRolePerm extends TableImpl<SecRelRolePermRecord> {

    private static final long serialVersionUID = 2030067934;

    /**
     * The reference instance of <code>DB_HTL.SEC_REL_ROLE_PERM</code>
     */
    public static final SecRelRolePerm SEC_REL_ROLE_PERM = new SecRelRolePerm();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecRelRolePermRecord> getRecordType() {
        return SecRelRolePermRecord.class;
    }

    /**
     * The column <code>DB_HTL.SEC_REL_ROLE_PERM.R_PERMISSION_ID</code>. permissionId,R_PERMISSION_ID
     */
    public final TableField<SecRelRolePermRecord, String> R_PERMISSION_ID = createField("R_PERMISSION_ID", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "permissionId,R_PERMISSION_ID");

    /**
     * The column <code>DB_HTL.SEC_REL_ROLE_PERM.R_ROLE_ID</code>. roleId,R_ROLE_ID
     */
    public final TableField<SecRelRolePermRecord, String> R_ROLE_ID = createField("R_ROLE_ID", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "roleId,R_ROLE_ID");

    /**
     * Create a <code>DB_HTL.SEC_REL_ROLE_PERM</code> table reference
     */
    public SecRelRolePerm() {
        this(DSL.name("SEC_REL_ROLE_PERM"), null);
    }

    /**
     * Create an aliased <code>DB_HTL.SEC_REL_ROLE_PERM</code> table reference
     */
    public SecRelRolePerm(String alias) {
        this(DSL.name(alias), SEC_REL_ROLE_PERM);
    }

    /**
     * Create an aliased <code>DB_HTL.SEC_REL_ROLE_PERM</code> table reference
     */
    public SecRelRolePerm(Name alias) {
        this(alias, SEC_REL_ROLE_PERM);
    }

    private SecRelRolePerm(Name alias, Table<SecRelRolePermRecord> aliased) {
        this(alias, aliased, null);
    }

    private SecRelRolePerm(Name alias, Table<SecRelRolePermRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbHtl.DB_HTL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SEC_REL_ROLE_PERM_FK_REL_RP_PERMISSION, Indexes.SEC_REL_ROLE_PERM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SecRelRolePermRecord> getPrimaryKey() {
        return Keys.KEY_SEC_REL_ROLE_PERM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SecRelRolePermRecord>> getKeys() {
        return Arrays.<UniqueKey<SecRelRolePermRecord>>asList(Keys.KEY_SEC_REL_ROLE_PERM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecRelRolePerm as(String alias) {
        return new SecRelRolePerm(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecRelRolePerm as(Name alias) {
        return new SecRelRolePerm(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecRelRolePerm rename(String name) {
        return new SecRelRolePerm(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecRelRolePerm rename(Name name) {
        return new SecRelRolePerm(name, null);
    }
}
