/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.pojos;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import up.god.jooq.tables.interfaces.IAtmBill;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AtmBill implements IAtmBill {

    private static final long serialVersionUID = 1753922524;

    private String        pkId;
    private BigDecimal    dAmountPrice;
    private String        tComment;
    private String        sCode;
    private String        sCredence;
    private String        sSerial;
    private String        jConfig;
    private Long          rltBillType;
    private Long          rOrderId;
    private String        rPaytermId;
    private Boolean       isIncome;
    private Boolean       isInvoice;
    private Boolean       isActive;
    private String        zSigma;
    private String        zLanguage;
    private String        zCreateBy;
    private LocalDateTime zCreateTime;
    private String        zUpdateBy;
    private LocalDateTime zUpdateTime;

    public AtmBill() {}

    public AtmBill(AtmBill value) {
        this.pkId = value.pkId;
        this.dAmountPrice = value.dAmountPrice;
        this.tComment = value.tComment;
        this.sCode = value.sCode;
        this.sCredence = value.sCredence;
        this.sSerial = value.sSerial;
        this.jConfig = value.jConfig;
        this.rltBillType = value.rltBillType;
        this.rOrderId = value.rOrderId;
        this.rPaytermId = value.rPaytermId;
        this.isIncome = value.isIncome;
        this.isInvoice = value.isInvoice;
        this.isActive = value.isActive;
        this.zSigma = value.zSigma;
        this.zLanguage = value.zLanguage;
        this.zCreateBy = value.zCreateBy;
        this.zCreateTime = value.zCreateTime;
        this.zUpdateBy = value.zUpdateBy;
        this.zUpdateTime = value.zUpdateTime;
    }

    public AtmBill(
        String        pkId,
        BigDecimal    dAmountPrice,
        String        tComment,
        String        sCode,
        String        sCredence,
        String        sSerial,
        String        jConfig,
        Long          rltBillType,
        Long          rOrderId,
        String        rPaytermId,
        Boolean       isIncome,
        Boolean       isInvoice,
        Boolean       isActive,
        String        zSigma,
        String        zLanguage,
        String        zCreateBy,
        LocalDateTime zCreateTime,
        String        zUpdateBy,
        LocalDateTime zUpdateTime
    ) {
        this.pkId = pkId;
        this.dAmountPrice = dAmountPrice;
        this.tComment = tComment;
        this.sCode = sCode;
        this.sCredence = sCredence;
        this.sSerial = sSerial;
        this.jConfig = jConfig;
        this.rltBillType = rltBillType;
        this.rOrderId = rOrderId;
        this.rPaytermId = rPaytermId;
        this.isIncome = isIncome;
        this.isInvoice = isInvoice;
        this.isActive = isActive;
        this.zSigma = zSigma;
        this.zLanguage = zLanguage;
        this.zCreateBy = zCreateBy;
        this.zCreateTime = zCreateTime;
        this.zUpdateBy = zUpdateBy;
        this.zUpdateTime = zUpdateTime;
    }

    @Override
    public String getPkId() {
        return this.pkId;
    }

    @Override
    public AtmBill setPkId(String pkId) {
        this.pkId = pkId;
        return this;
    }

    @Override
    public BigDecimal getDAmountPrice() {
        return this.dAmountPrice;
    }

    @Override
    public AtmBill setDAmountPrice(BigDecimal dAmountPrice) {
        this.dAmountPrice = dAmountPrice;
        return this;
    }

    @Override
    public String getTComment() {
        return this.tComment;
    }

    @Override
    public AtmBill setTComment(String tComment) {
        this.tComment = tComment;
        return this;
    }

    @Override
    public String getSCode() {
        return this.sCode;
    }

    @Override
    public AtmBill setSCode(String sCode) {
        this.sCode = sCode;
        return this;
    }

    @Override
    public String getSCredence() {
        return this.sCredence;
    }

    @Override
    public AtmBill setSCredence(String sCredence) {
        this.sCredence = sCredence;
        return this;
    }

    @Override
    public String getSSerial() {
        return this.sSerial;
    }

    @Override
    public AtmBill setSSerial(String sSerial) {
        this.sSerial = sSerial;
        return this;
    }

    @Override
    public String getJConfig() {
        return this.jConfig;
    }

    @Override
    public AtmBill setJConfig(String jConfig) {
        this.jConfig = jConfig;
        return this;
    }

    @Override
    public Long getRltBillType() {
        return this.rltBillType;
    }

    @Override
    public AtmBill setRltBillType(Long rltBillType) {
        this.rltBillType = rltBillType;
        return this;
    }

    @Override
    public Long getROrderId() {
        return this.rOrderId;
    }

    @Override
    public AtmBill setROrderId(Long rOrderId) {
        this.rOrderId = rOrderId;
        return this;
    }

    @Override
    public String getRPaytermId() {
        return this.rPaytermId;
    }

    @Override
    public AtmBill setRPaytermId(String rPaytermId) {
        this.rPaytermId = rPaytermId;
        return this;
    }

    @Override
    public Boolean getIsIncome() {
        return this.isIncome;
    }

    @Override
    public AtmBill setIsIncome(Boolean isIncome) {
        this.isIncome = isIncome;
        return this;
    }

    @Override
    public Boolean getIsInvoice() {
        return this.isInvoice;
    }

    @Override
    public AtmBill setIsInvoice(Boolean isInvoice) {
        this.isInvoice = isInvoice;
        return this;
    }

    @Override
    public Boolean getIsActive() {
        return this.isActive;
    }

    @Override
    public AtmBill setIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }

    @Override
    public String getZSigma() {
        return this.zSigma;
    }

    @Override
    public AtmBill setZSigma(String zSigma) {
        this.zSigma = zSigma;
        return this;
    }

    @Override
    public String getZLanguage() {
        return this.zLanguage;
    }

    @Override
    public AtmBill setZLanguage(String zLanguage) {
        this.zLanguage = zLanguage;
        return this;
    }

    @Override
    public String getZCreateBy() {
        return this.zCreateBy;
    }

    @Override
    public AtmBill setZCreateBy(String zCreateBy) {
        this.zCreateBy = zCreateBy;
        return this;
    }

    @Override
    public LocalDateTime getZCreateTime() {
        return this.zCreateTime;
    }

    @Override
    public AtmBill setZCreateTime(LocalDateTime zCreateTime) {
        this.zCreateTime = zCreateTime;
        return this;
    }

    @Override
    public String getZUpdateBy() {
        return this.zUpdateBy;
    }

    @Override
    public AtmBill setZUpdateBy(String zUpdateBy) {
        this.zUpdateBy = zUpdateBy;
        return this;
    }

    @Override
    public LocalDateTime getZUpdateTime() {
        return this.zUpdateTime;
    }

    @Override
    public AtmBill setZUpdateTime(LocalDateTime zUpdateTime) {
        this.zUpdateTime = zUpdateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AtmBill (");

        sb.append(pkId);
        sb.append(", ").append(dAmountPrice);
        sb.append(", ").append(tComment);
        sb.append(", ").append(sCode);
        sb.append(", ").append(sCredence);
        sb.append(", ").append(sSerial);
        sb.append(", ").append(jConfig);
        sb.append(", ").append(rltBillType);
        sb.append(", ").append(rOrderId);
        sb.append(", ").append(rPaytermId);
        sb.append(", ").append(isIncome);
        sb.append(", ").append(isInvoice);
        sb.append(", ").append(isActive);
        sb.append(", ").append(zSigma);
        sb.append(", ").append(zLanguage);
        sb.append(", ").append(zCreateBy);
        sb.append(", ").append(zCreateTime);
        sb.append(", ").append(zUpdateBy);
        sb.append(", ").append(zUpdateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IAtmBill from) {
        setPkId(from.getPkId());
        setDAmountPrice(from.getDAmountPrice());
        setTComment(from.getTComment());
        setSCode(from.getSCode());
        setSCredence(from.getSCredence());
        setSSerial(from.getSSerial());
        setJConfig(from.getJConfig());
        setRltBillType(from.getRltBillType());
        setROrderId(from.getROrderId());
        setRPaytermId(from.getRPaytermId());
        setIsIncome(from.getIsIncome());
        setIsInvoice(from.getIsInvoice());
        setIsActive(from.getIsActive());
        setZSigma(from.getZSigma());
        setZLanguage(from.getZLanguage());
        setZCreateBy(from.getZCreateBy());
        setZCreateTime(from.getZCreateTime());
        setZUpdateBy(from.getZUpdateBy());
        setZUpdateTime(from.getZUpdateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IAtmBill> E into(E into) {
        into.from(this);
        return into;
    }

    public AtmBill(io.vertx.core.json.JsonObject json) {
        fromJson(json);
    }
}
