/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.pojos;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import up.god.jooq.tables.interfaces.IAtmPayterm;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AtmPayterm implements IAtmPayterm {

    private static final long serialVersionUID = -1975048391;

    private String        pkId;
    private BigDecimal    dPrice;
    private String        tComment;
    private String        vAccountId;
    private String        sName;
    private String        sCode;
    private String        sHelpCode;
    private String        sType;
    private String        sUnit;
    private String        jConfig;
    private String        rCategoryId;
    private Long          rCompanyId;
    private Boolean       isDetail;
    private Boolean       isActive;
    private String        zSigma;
    private String        zLanguage;
    private String        zCreateBy;
    private LocalDateTime zCreateTime;
    private String        zUpdateBy;
    private LocalDateTime zUpdateTime;

    public AtmPayterm() {}

    public AtmPayterm(AtmPayterm value) {
        this.pkId = value.pkId;
        this.dPrice = value.dPrice;
        this.tComment = value.tComment;
        this.vAccountId = value.vAccountId;
        this.sName = value.sName;
        this.sCode = value.sCode;
        this.sHelpCode = value.sHelpCode;
        this.sType = value.sType;
        this.sUnit = value.sUnit;
        this.jConfig = value.jConfig;
        this.rCategoryId = value.rCategoryId;
        this.rCompanyId = value.rCompanyId;
        this.isDetail = value.isDetail;
        this.isActive = value.isActive;
        this.zSigma = value.zSigma;
        this.zLanguage = value.zLanguage;
        this.zCreateBy = value.zCreateBy;
        this.zCreateTime = value.zCreateTime;
        this.zUpdateBy = value.zUpdateBy;
        this.zUpdateTime = value.zUpdateTime;
    }

    public AtmPayterm(
        String        pkId,
        BigDecimal    dPrice,
        String        tComment,
        String        vAccountId,
        String        sName,
        String        sCode,
        String        sHelpCode,
        String        sType,
        String        sUnit,
        String        jConfig,
        String        rCategoryId,
        Long          rCompanyId,
        Boolean       isDetail,
        Boolean       isActive,
        String        zSigma,
        String        zLanguage,
        String        zCreateBy,
        LocalDateTime zCreateTime,
        String        zUpdateBy,
        LocalDateTime zUpdateTime
    ) {
        this.pkId = pkId;
        this.dPrice = dPrice;
        this.tComment = tComment;
        this.vAccountId = vAccountId;
        this.sName = sName;
        this.sCode = sCode;
        this.sHelpCode = sHelpCode;
        this.sType = sType;
        this.sUnit = sUnit;
        this.jConfig = jConfig;
        this.rCategoryId = rCategoryId;
        this.rCompanyId = rCompanyId;
        this.isDetail = isDetail;
        this.isActive = isActive;
        this.zSigma = zSigma;
        this.zLanguage = zLanguage;
        this.zCreateBy = zCreateBy;
        this.zCreateTime = zCreateTime;
        this.zUpdateBy = zUpdateBy;
        this.zUpdateTime = zUpdateTime;
    }

    @Override
    public String getPkId() {
        return this.pkId;
    }

    @Override
    public AtmPayterm setPkId(String pkId) {
        this.pkId = pkId;
        return this;
    }

    @Override
    public BigDecimal getDPrice() {
        return this.dPrice;
    }

    @Override
    public AtmPayterm setDPrice(BigDecimal dPrice) {
        this.dPrice = dPrice;
        return this;
    }

    @Override
    public String getTComment() {
        return this.tComment;
    }

    @Override
    public AtmPayterm setTComment(String tComment) {
        this.tComment = tComment;
        return this;
    }

    @Override
    public String getVAccountId() {
        return this.vAccountId;
    }

    @Override
    public AtmPayterm setVAccountId(String vAccountId) {
        this.vAccountId = vAccountId;
        return this;
    }

    @Override
    public String getSName() {
        return this.sName;
    }

    @Override
    public AtmPayterm setSName(String sName) {
        this.sName = sName;
        return this;
    }

    @Override
    public String getSCode() {
        return this.sCode;
    }

    @Override
    public AtmPayterm setSCode(String sCode) {
        this.sCode = sCode;
        return this;
    }

    @Override
    public String getSHelpCode() {
        return this.sHelpCode;
    }

    @Override
    public AtmPayterm setSHelpCode(String sHelpCode) {
        this.sHelpCode = sHelpCode;
        return this;
    }

    @Override
    public String getSType() {
        return this.sType;
    }

    @Override
    public AtmPayterm setSType(String sType) {
        this.sType = sType;
        return this;
    }

    @Override
    public String getSUnit() {
        return this.sUnit;
    }

    @Override
    public AtmPayterm setSUnit(String sUnit) {
        this.sUnit = sUnit;
        return this;
    }

    @Override
    public String getJConfig() {
        return this.jConfig;
    }

    @Override
    public AtmPayterm setJConfig(String jConfig) {
        this.jConfig = jConfig;
        return this;
    }

    @Override
    public String getRCategoryId() {
        return this.rCategoryId;
    }

    @Override
    public AtmPayterm setRCategoryId(String rCategoryId) {
        this.rCategoryId = rCategoryId;
        return this;
    }

    @Override
    public Long getRCompanyId() {
        return this.rCompanyId;
    }

    @Override
    public AtmPayterm setRCompanyId(Long rCompanyId) {
        this.rCompanyId = rCompanyId;
        return this;
    }

    @Override
    public Boolean getIsDetail() {
        return this.isDetail;
    }

    @Override
    public AtmPayterm setIsDetail(Boolean isDetail) {
        this.isDetail = isDetail;
        return this;
    }

    @Override
    public Boolean getIsActive() {
        return this.isActive;
    }

    @Override
    public AtmPayterm setIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }

    @Override
    public String getZSigma() {
        return this.zSigma;
    }

    @Override
    public AtmPayterm setZSigma(String zSigma) {
        this.zSigma = zSigma;
        return this;
    }

    @Override
    public String getZLanguage() {
        return this.zLanguage;
    }

    @Override
    public AtmPayterm setZLanguage(String zLanguage) {
        this.zLanguage = zLanguage;
        return this;
    }

    @Override
    public String getZCreateBy() {
        return this.zCreateBy;
    }

    @Override
    public AtmPayterm setZCreateBy(String zCreateBy) {
        this.zCreateBy = zCreateBy;
        return this;
    }

    @Override
    public LocalDateTime getZCreateTime() {
        return this.zCreateTime;
    }

    @Override
    public AtmPayterm setZCreateTime(LocalDateTime zCreateTime) {
        this.zCreateTime = zCreateTime;
        return this;
    }

    @Override
    public String getZUpdateBy() {
        return this.zUpdateBy;
    }

    @Override
    public AtmPayterm setZUpdateBy(String zUpdateBy) {
        this.zUpdateBy = zUpdateBy;
        return this;
    }

    @Override
    public LocalDateTime getZUpdateTime() {
        return this.zUpdateTime;
    }

    @Override
    public AtmPayterm setZUpdateTime(LocalDateTime zUpdateTime) {
        this.zUpdateTime = zUpdateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AtmPayterm (");

        sb.append(pkId);
        sb.append(", ").append(dPrice);
        sb.append(", ").append(tComment);
        sb.append(", ").append(vAccountId);
        sb.append(", ").append(sName);
        sb.append(", ").append(sCode);
        sb.append(", ").append(sHelpCode);
        sb.append(", ").append(sType);
        sb.append(", ").append(sUnit);
        sb.append(", ").append(jConfig);
        sb.append(", ").append(rCategoryId);
        sb.append(", ").append(rCompanyId);
        sb.append(", ").append(isDetail);
        sb.append(", ").append(isActive);
        sb.append(", ").append(zSigma);
        sb.append(", ").append(zLanguage);
        sb.append(", ").append(zCreateBy);
        sb.append(", ").append(zCreateTime);
        sb.append(", ").append(zUpdateBy);
        sb.append(", ").append(zUpdateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IAtmPayterm from) {
        setPkId(from.getPkId());
        setDPrice(from.getDPrice());
        setTComment(from.getTComment());
        setVAccountId(from.getVAccountId());
        setSName(from.getSName());
        setSCode(from.getSCode());
        setSHelpCode(from.getSHelpCode());
        setSType(from.getSType());
        setSUnit(from.getSUnit());
        setJConfig(from.getJConfig());
        setRCategoryId(from.getRCategoryId());
        setRCompanyId(from.getRCompanyId());
        setIsDetail(from.getIsDetail());
        setIsActive(from.getIsActive());
        setZSigma(from.getZSigma());
        setZLanguage(from.getZLanguage());
        setZCreateBy(from.getZCreateBy());
        setZCreateTime(from.getZCreateTime());
        setZUpdateBy(from.getZUpdateBy());
        setZUpdateTime(from.getZUpdateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IAtmPayterm> E into(E into) {
        into.from(this);
        return into;
    }

    public AtmPayterm(io.vertx.core.json.JsonObject json) {
        fromJson(json);
    }
}
