/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.pojos;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import up.god.jooq.tables.interfaces.IEcmShop;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EcmShop implements IEcmShop {

    private static final long serialVersionUID = 61357379;

    private Long          pkId;
    private String        tComment;
    private String        vSupportId;
    private String        sName;
    private String        sCode;
    private String        sKeyword;
    private String        sOwnername;
    private String        sSupportEmail;
    private String        sSupportMobile;
    private String        sSupportQq;
    private String        sTitle;
    private String        jConfig;
    private Long          rltType;
    private Long          rLocationId;
    private String        rOwnerId;
    private Boolean       isActive;
    private String        zSigma;
    private String        zLanguage;
    private String        zCreateBy;
    private LocalDateTime zCreateTime;
    private String        zUpdateBy;
    private LocalDateTime zUpdateTime;

    public EcmShop() {}

    public EcmShop(EcmShop value) {
        this.pkId = value.pkId;
        this.tComment = value.tComment;
        this.vSupportId = value.vSupportId;
        this.sName = value.sName;
        this.sCode = value.sCode;
        this.sKeyword = value.sKeyword;
        this.sOwnername = value.sOwnername;
        this.sSupportEmail = value.sSupportEmail;
        this.sSupportMobile = value.sSupportMobile;
        this.sSupportQq = value.sSupportQq;
        this.sTitle = value.sTitle;
        this.jConfig = value.jConfig;
        this.rltType = value.rltType;
        this.rLocationId = value.rLocationId;
        this.rOwnerId = value.rOwnerId;
        this.isActive = value.isActive;
        this.zSigma = value.zSigma;
        this.zLanguage = value.zLanguage;
        this.zCreateBy = value.zCreateBy;
        this.zCreateTime = value.zCreateTime;
        this.zUpdateBy = value.zUpdateBy;
        this.zUpdateTime = value.zUpdateTime;
    }

    public EcmShop(
        Long          pkId,
        String        tComment,
        String        vSupportId,
        String        sName,
        String        sCode,
        String        sKeyword,
        String        sOwnername,
        String        sSupportEmail,
        String        sSupportMobile,
        String        sSupportQq,
        String        sTitle,
        String        jConfig,
        Long          rltType,
        Long          rLocationId,
        String        rOwnerId,
        Boolean       isActive,
        String        zSigma,
        String        zLanguage,
        String        zCreateBy,
        LocalDateTime zCreateTime,
        String        zUpdateBy,
        LocalDateTime zUpdateTime
    ) {
        this.pkId = pkId;
        this.tComment = tComment;
        this.vSupportId = vSupportId;
        this.sName = sName;
        this.sCode = sCode;
        this.sKeyword = sKeyword;
        this.sOwnername = sOwnername;
        this.sSupportEmail = sSupportEmail;
        this.sSupportMobile = sSupportMobile;
        this.sSupportQq = sSupportQq;
        this.sTitle = sTitle;
        this.jConfig = jConfig;
        this.rltType = rltType;
        this.rLocationId = rLocationId;
        this.rOwnerId = rOwnerId;
        this.isActive = isActive;
        this.zSigma = zSigma;
        this.zLanguage = zLanguage;
        this.zCreateBy = zCreateBy;
        this.zCreateTime = zCreateTime;
        this.zUpdateBy = zUpdateBy;
        this.zUpdateTime = zUpdateTime;
    }

    @Override
    public Long getPkId() {
        return this.pkId;
    }

    @Override
    public EcmShop setPkId(Long pkId) {
        this.pkId = pkId;
        return this;
    }

    @Override
    public String getTComment() {
        return this.tComment;
    }

    @Override
    public EcmShop setTComment(String tComment) {
        this.tComment = tComment;
        return this;
    }

    @Override
    public String getVSupportId() {
        return this.vSupportId;
    }

    @Override
    public EcmShop setVSupportId(String vSupportId) {
        this.vSupportId = vSupportId;
        return this;
    }

    @Override
    public String getSName() {
        return this.sName;
    }

    @Override
    public EcmShop setSName(String sName) {
        this.sName = sName;
        return this;
    }

    @Override
    public String getSCode() {
        return this.sCode;
    }

    @Override
    public EcmShop setSCode(String sCode) {
        this.sCode = sCode;
        return this;
    }

    @Override
    public String getSKeyword() {
        return this.sKeyword;
    }

    @Override
    public EcmShop setSKeyword(String sKeyword) {
        this.sKeyword = sKeyword;
        return this;
    }

    @Override
    public String getSOwnername() {
        return this.sOwnername;
    }

    @Override
    public EcmShop setSOwnername(String sOwnername) {
        this.sOwnername = sOwnername;
        return this;
    }

    @Override
    public String getSSupportEmail() {
        return this.sSupportEmail;
    }

    @Override
    public EcmShop setSSupportEmail(String sSupportEmail) {
        this.sSupportEmail = sSupportEmail;
        return this;
    }

    @Override
    public String getSSupportMobile() {
        return this.sSupportMobile;
    }

    @Override
    public EcmShop setSSupportMobile(String sSupportMobile) {
        this.sSupportMobile = sSupportMobile;
        return this;
    }

    @Override
    public String getSSupportQq() {
        return this.sSupportQq;
    }

    @Override
    public EcmShop setSSupportQq(String sSupportQq) {
        this.sSupportQq = sSupportQq;
        return this;
    }

    @Override
    public String getSTitle() {
        return this.sTitle;
    }

    @Override
    public EcmShop setSTitle(String sTitle) {
        this.sTitle = sTitle;
        return this;
    }

    @Override
    public String getJConfig() {
        return this.jConfig;
    }

    @Override
    public EcmShop setJConfig(String jConfig) {
        this.jConfig = jConfig;
        return this;
    }

    @Override
    public Long getRltType() {
        return this.rltType;
    }

    @Override
    public EcmShop setRltType(Long rltType) {
        this.rltType = rltType;
        return this;
    }

    @Override
    public Long getRLocationId() {
        return this.rLocationId;
    }

    @Override
    public EcmShop setRLocationId(Long rLocationId) {
        this.rLocationId = rLocationId;
        return this;
    }

    @Override
    public String getROwnerId() {
        return this.rOwnerId;
    }

    @Override
    public EcmShop setROwnerId(String rOwnerId) {
        this.rOwnerId = rOwnerId;
        return this;
    }

    @Override
    public Boolean getIsActive() {
        return this.isActive;
    }

    @Override
    public EcmShop setIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }

    @Override
    public String getZSigma() {
        return this.zSigma;
    }

    @Override
    public EcmShop setZSigma(String zSigma) {
        this.zSigma = zSigma;
        return this;
    }

    @Override
    public String getZLanguage() {
        return this.zLanguage;
    }

    @Override
    public EcmShop setZLanguage(String zLanguage) {
        this.zLanguage = zLanguage;
        return this;
    }

    @Override
    public String getZCreateBy() {
        return this.zCreateBy;
    }

    @Override
    public EcmShop setZCreateBy(String zCreateBy) {
        this.zCreateBy = zCreateBy;
        return this;
    }

    @Override
    public LocalDateTime getZCreateTime() {
        return this.zCreateTime;
    }

    @Override
    public EcmShop setZCreateTime(LocalDateTime zCreateTime) {
        this.zCreateTime = zCreateTime;
        return this;
    }

    @Override
    public String getZUpdateBy() {
        return this.zUpdateBy;
    }

    @Override
    public EcmShop setZUpdateBy(String zUpdateBy) {
        this.zUpdateBy = zUpdateBy;
        return this;
    }

    @Override
    public LocalDateTime getZUpdateTime() {
        return this.zUpdateTime;
    }

    @Override
    public EcmShop setZUpdateTime(LocalDateTime zUpdateTime) {
        this.zUpdateTime = zUpdateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EcmShop (");

        sb.append(pkId);
        sb.append(", ").append(tComment);
        sb.append(", ").append(vSupportId);
        sb.append(", ").append(sName);
        sb.append(", ").append(sCode);
        sb.append(", ").append(sKeyword);
        sb.append(", ").append(sOwnername);
        sb.append(", ").append(sSupportEmail);
        sb.append(", ").append(sSupportMobile);
        sb.append(", ").append(sSupportQq);
        sb.append(", ").append(sTitle);
        sb.append(", ").append(jConfig);
        sb.append(", ").append(rltType);
        sb.append(", ").append(rLocationId);
        sb.append(", ").append(rOwnerId);
        sb.append(", ").append(isActive);
        sb.append(", ").append(zSigma);
        sb.append(", ").append(zLanguage);
        sb.append(", ").append(zCreateBy);
        sb.append(", ").append(zCreateTime);
        sb.append(", ").append(zUpdateBy);
        sb.append(", ").append(zUpdateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IEcmShop from) {
        setPkId(from.getPkId());
        setTComment(from.getTComment());
        setVSupportId(from.getVSupportId());
        setSName(from.getSName());
        setSCode(from.getSCode());
        setSKeyword(from.getSKeyword());
        setSOwnername(from.getSOwnername());
        setSSupportEmail(from.getSSupportEmail());
        setSSupportMobile(from.getSSupportMobile());
        setSSupportQq(from.getSSupportQq());
        setSTitle(from.getSTitle());
        setJConfig(from.getJConfig());
        setRltType(from.getRltType());
        setRLocationId(from.getRLocationId());
        setROwnerId(from.getROwnerId());
        setIsActive(from.getIsActive());
        setZSigma(from.getZSigma());
        setZLanguage(from.getZLanguage());
        setZCreateBy(from.getZCreateBy());
        setZCreateTime(from.getZCreateTime());
        setZUpdateBy(from.getZUpdateBy());
        setZUpdateTime(from.getZUpdateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IEcmShop> E into(E into) {
        into.from(this);
        return into;
    }

    public EcmShop(io.vertx.core.json.JsonObject json) {
        fromJson(json);
    }
}
