/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.pojos;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import up.god.jooq.tables.interfaces.IPsiOrdIn;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PsiOrdIn implements IPsiOrdIn {

    private static final long serialVersionUID = 1943589120;

    private String        pkId;
    private String        tComment;
    private String        sName;
    private String        sCode;
    private String        sGodown;
    private String        sHandler;
    private String        sManager;
    private String        sOperator;
    private String        jConfig;
    private Long          rOrderId;
    private Long          rWhId;
    private Boolean       isActive;
    private String        zSigma;
    private String        zLanguage;
    private String        zCreateBy;
    private LocalDateTime zCreateTime;
    private String        zUpdateBy;
    private LocalDateTime zUpdateTime;

    public PsiOrdIn() {}

    public PsiOrdIn(PsiOrdIn value) {
        this.pkId = value.pkId;
        this.tComment = value.tComment;
        this.sName = value.sName;
        this.sCode = value.sCode;
        this.sGodown = value.sGodown;
        this.sHandler = value.sHandler;
        this.sManager = value.sManager;
        this.sOperator = value.sOperator;
        this.jConfig = value.jConfig;
        this.rOrderId = value.rOrderId;
        this.rWhId = value.rWhId;
        this.isActive = value.isActive;
        this.zSigma = value.zSigma;
        this.zLanguage = value.zLanguage;
        this.zCreateBy = value.zCreateBy;
        this.zCreateTime = value.zCreateTime;
        this.zUpdateBy = value.zUpdateBy;
        this.zUpdateTime = value.zUpdateTime;
    }

    public PsiOrdIn(
        String        pkId,
        String        tComment,
        String        sName,
        String        sCode,
        String        sGodown,
        String        sHandler,
        String        sManager,
        String        sOperator,
        String        jConfig,
        Long          rOrderId,
        Long          rWhId,
        Boolean       isActive,
        String        zSigma,
        String        zLanguage,
        String        zCreateBy,
        LocalDateTime zCreateTime,
        String        zUpdateBy,
        LocalDateTime zUpdateTime
    ) {
        this.pkId = pkId;
        this.tComment = tComment;
        this.sName = sName;
        this.sCode = sCode;
        this.sGodown = sGodown;
        this.sHandler = sHandler;
        this.sManager = sManager;
        this.sOperator = sOperator;
        this.jConfig = jConfig;
        this.rOrderId = rOrderId;
        this.rWhId = rWhId;
        this.isActive = isActive;
        this.zSigma = zSigma;
        this.zLanguage = zLanguage;
        this.zCreateBy = zCreateBy;
        this.zCreateTime = zCreateTime;
        this.zUpdateBy = zUpdateBy;
        this.zUpdateTime = zUpdateTime;
    }

    @Override
    public String getPkId() {
        return this.pkId;
    }

    @Override
    public PsiOrdIn setPkId(String pkId) {
        this.pkId = pkId;
        return this;
    }

    @Override
    public String getTComment() {
        return this.tComment;
    }

    @Override
    public PsiOrdIn setTComment(String tComment) {
        this.tComment = tComment;
        return this;
    }

    @Override
    public String getSName() {
        return this.sName;
    }

    @Override
    public PsiOrdIn setSName(String sName) {
        this.sName = sName;
        return this;
    }

    @Override
    public String getSCode() {
        return this.sCode;
    }

    @Override
    public PsiOrdIn setSCode(String sCode) {
        this.sCode = sCode;
        return this;
    }

    @Override
    public String getSGodown() {
        return this.sGodown;
    }

    @Override
    public PsiOrdIn setSGodown(String sGodown) {
        this.sGodown = sGodown;
        return this;
    }

    @Override
    public String getSHandler() {
        return this.sHandler;
    }

    @Override
    public PsiOrdIn setSHandler(String sHandler) {
        this.sHandler = sHandler;
        return this;
    }

    @Override
    public String getSManager() {
        return this.sManager;
    }

    @Override
    public PsiOrdIn setSManager(String sManager) {
        this.sManager = sManager;
        return this;
    }

    @Override
    public String getSOperator() {
        return this.sOperator;
    }

    @Override
    public PsiOrdIn setSOperator(String sOperator) {
        this.sOperator = sOperator;
        return this;
    }

    @Override
    public String getJConfig() {
        return this.jConfig;
    }

    @Override
    public PsiOrdIn setJConfig(String jConfig) {
        this.jConfig = jConfig;
        return this;
    }

    @Override
    public Long getROrderId() {
        return this.rOrderId;
    }

    @Override
    public PsiOrdIn setROrderId(Long rOrderId) {
        this.rOrderId = rOrderId;
        return this;
    }

    @Override
    public Long getRWhId() {
        return this.rWhId;
    }

    @Override
    public PsiOrdIn setRWhId(Long rWhId) {
        this.rWhId = rWhId;
        return this;
    }

    @Override
    public Boolean getIsActive() {
        return this.isActive;
    }

    @Override
    public PsiOrdIn setIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }

    @Override
    public String getZSigma() {
        return this.zSigma;
    }

    @Override
    public PsiOrdIn setZSigma(String zSigma) {
        this.zSigma = zSigma;
        return this;
    }

    @Override
    public String getZLanguage() {
        return this.zLanguage;
    }

    @Override
    public PsiOrdIn setZLanguage(String zLanguage) {
        this.zLanguage = zLanguage;
        return this;
    }

    @Override
    public String getZCreateBy() {
        return this.zCreateBy;
    }

    @Override
    public PsiOrdIn setZCreateBy(String zCreateBy) {
        this.zCreateBy = zCreateBy;
        return this;
    }

    @Override
    public LocalDateTime getZCreateTime() {
        return this.zCreateTime;
    }

    @Override
    public PsiOrdIn setZCreateTime(LocalDateTime zCreateTime) {
        this.zCreateTime = zCreateTime;
        return this;
    }

    @Override
    public String getZUpdateBy() {
        return this.zUpdateBy;
    }

    @Override
    public PsiOrdIn setZUpdateBy(String zUpdateBy) {
        this.zUpdateBy = zUpdateBy;
        return this;
    }

    @Override
    public LocalDateTime getZUpdateTime() {
        return this.zUpdateTime;
    }

    @Override
    public PsiOrdIn setZUpdateTime(LocalDateTime zUpdateTime) {
        this.zUpdateTime = zUpdateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PsiOrdIn (");

        sb.append(pkId);
        sb.append(", ").append(tComment);
        sb.append(", ").append(sName);
        sb.append(", ").append(sCode);
        sb.append(", ").append(sGodown);
        sb.append(", ").append(sHandler);
        sb.append(", ").append(sManager);
        sb.append(", ").append(sOperator);
        sb.append(", ").append(jConfig);
        sb.append(", ").append(rOrderId);
        sb.append(", ").append(rWhId);
        sb.append(", ").append(isActive);
        sb.append(", ").append(zSigma);
        sb.append(", ").append(zLanguage);
        sb.append(", ").append(zCreateBy);
        sb.append(", ").append(zCreateTime);
        sb.append(", ").append(zUpdateBy);
        sb.append(", ").append(zUpdateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IPsiOrdIn from) {
        setPkId(from.getPkId());
        setTComment(from.getTComment());
        setSName(from.getSName());
        setSCode(from.getSCode());
        setSGodown(from.getSGodown());
        setSHandler(from.getSHandler());
        setSManager(from.getSManager());
        setSOperator(from.getSOperator());
        setJConfig(from.getJConfig());
        setROrderId(from.getROrderId());
        setRWhId(from.getRWhId());
        setIsActive(from.getIsActive());
        setZSigma(from.getZSigma());
        setZLanguage(from.getZLanguage());
        setZCreateBy(from.getZCreateBy());
        setZCreateTime(from.getZCreateTime());
        setZUpdateBy(from.getZUpdateBy());
        setZUpdateTime(from.getZUpdateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IPsiOrdIn> E into(E into) {
        into.from(this);
        return into;
    }

    public PsiOrdIn(io.vertx.core.json.JsonObject json) {
        fromJson(json);
    }
}
