/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.pojos;


import javax.annotation.Generated;

import up.god.jooq.tables.interfaces.ISecRelRolePerm;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecRelRolePerm implements ISecRelRolePerm {

    private static final long serialVersionUID = 2086503340;

    private String rPermissionId;
    private String rRoleId;

    public SecRelRolePerm() {}

    public SecRelRolePerm(SecRelRolePerm value) {
        this.rPermissionId = value.rPermissionId;
        this.rRoleId = value.rRoleId;
    }

    public SecRelRolePerm(
        String rPermissionId,
        String rRoleId
    ) {
        this.rPermissionId = rPermissionId;
        this.rRoleId = rRoleId;
    }

    @Override
    public String getRPermissionId() {
        return this.rPermissionId;
    }

    @Override
    public SecRelRolePerm setRPermissionId(String rPermissionId) {
        this.rPermissionId = rPermissionId;
        return this;
    }

    @Override
    public String getRRoleId() {
        return this.rRoleId;
    }

    @Override
    public SecRelRolePerm setRRoleId(String rRoleId) {
        this.rRoleId = rRoleId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SecRelRolePerm (");

        sb.append(rPermissionId);
        sb.append(", ").append(rRoleId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ISecRelRolePerm from) {
        setRPermissionId(from.getRPermissionId());
        setRRoleId(from.getRRoleId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ISecRelRolePerm> E into(E into) {
        into.from(this);
        return into;
    }

    public SecRelRolePerm(io.vertx.core.json.JsonObject json) {
        fromJson(json);
    }
}
