/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.pojos;


import java.time.LocalDate;

import javax.annotation.Generated;

import up.god.jooq.tables.interfaces.IVHtlRoomOccup;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VHtlRoomOccup implements IVHtlRoomOccup {

    private static final long serialVersionUID = -1651952698;

    private Long      pkId;
    private String    sRoomNum;
    private Long      rTentId;
    private Long      rFloorId;
    private LocalDate dDay;
    private Long      rRoomTypeId;
    private Long      rltOpStatus;
    private Long      rltCleanStatus;
    private Boolean   isLeaving;
    private Boolean   isArriving;
    private Integer   iExceed;
    private Long      rHotelId;
    private String    zLanguage;

    public VHtlRoomOccup() {}

    public VHtlRoomOccup(VHtlRoomOccup value) {
        this.pkId = value.pkId;
        this.sRoomNum = value.sRoomNum;
        this.rTentId = value.rTentId;
        this.rFloorId = value.rFloorId;
        this.dDay = value.dDay;
        this.rRoomTypeId = value.rRoomTypeId;
        this.rltOpStatus = value.rltOpStatus;
        this.rltCleanStatus = value.rltCleanStatus;
        this.isLeaving = value.isLeaving;
        this.isArriving = value.isArriving;
        this.iExceed = value.iExceed;
        this.rHotelId = value.rHotelId;
        this.zLanguage = value.zLanguage;
    }

    public VHtlRoomOccup(
        Long      pkId,
        String    sRoomNum,
        Long      rTentId,
        Long      rFloorId,
        LocalDate dDay,
        Long      rRoomTypeId,
        Long      rltOpStatus,
        Long      rltCleanStatus,
        Boolean   isLeaving,
        Boolean   isArriving,
        Integer   iExceed,
        Long      rHotelId,
        String    zLanguage
    ) {
        this.pkId = pkId;
        this.sRoomNum = sRoomNum;
        this.rTentId = rTentId;
        this.rFloorId = rFloorId;
        this.dDay = dDay;
        this.rRoomTypeId = rRoomTypeId;
        this.rltOpStatus = rltOpStatus;
        this.rltCleanStatus = rltCleanStatus;
        this.isLeaving = isLeaving;
        this.isArriving = isArriving;
        this.iExceed = iExceed;
        this.rHotelId = rHotelId;
        this.zLanguage = zLanguage;
    }

    @Override
    public Long getPkId() {
        return this.pkId;
    }

    @Override
    public VHtlRoomOccup setPkId(Long pkId) {
        this.pkId = pkId;
        return this;
    }

    @Override
    public String getSRoomNum() {
        return this.sRoomNum;
    }

    @Override
    public VHtlRoomOccup setSRoomNum(String sRoomNum) {
        this.sRoomNum = sRoomNum;
        return this;
    }

    @Override
    public Long getRTentId() {
        return this.rTentId;
    }

    @Override
    public VHtlRoomOccup setRTentId(Long rTentId) {
        this.rTentId = rTentId;
        return this;
    }

    @Override
    public Long getRFloorId() {
        return this.rFloorId;
    }

    @Override
    public VHtlRoomOccup setRFloorId(Long rFloorId) {
        this.rFloorId = rFloorId;
        return this;
    }

    @Override
    public LocalDate getDDay() {
        return this.dDay;
    }

    @Override
    public VHtlRoomOccup setDDay(LocalDate dDay) {
        this.dDay = dDay;
        return this;
    }

    @Override
    public Long getRRoomTypeId() {
        return this.rRoomTypeId;
    }

    @Override
    public VHtlRoomOccup setRRoomTypeId(Long rRoomTypeId) {
        this.rRoomTypeId = rRoomTypeId;
        return this;
    }

    @Override
    public Long getRltOpStatus() {
        return this.rltOpStatus;
    }

    @Override
    public VHtlRoomOccup setRltOpStatus(Long rltOpStatus) {
        this.rltOpStatus = rltOpStatus;
        return this;
    }

    @Override
    public Long getRltCleanStatus() {
        return this.rltCleanStatus;
    }

    @Override
    public VHtlRoomOccup setRltCleanStatus(Long rltCleanStatus) {
        this.rltCleanStatus = rltCleanStatus;
        return this;
    }

    @Override
    public Boolean getIsLeaving() {
        return this.isLeaving;
    }

    @Override
    public VHtlRoomOccup setIsLeaving(Boolean isLeaving) {
        this.isLeaving = isLeaving;
        return this;
    }

    @Override
    public Boolean getIsArriving() {
        return this.isArriving;
    }

    @Override
    public VHtlRoomOccup setIsArriving(Boolean isArriving) {
        this.isArriving = isArriving;
        return this;
    }

    @Override
    public Integer getIExceed() {
        return this.iExceed;
    }

    @Override
    public VHtlRoomOccup setIExceed(Integer iExceed) {
        this.iExceed = iExceed;
        return this;
    }

    @Override
    public Long getRHotelId() {
        return this.rHotelId;
    }

    @Override
    public VHtlRoomOccup setRHotelId(Long rHotelId) {
        this.rHotelId = rHotelId;
        return this;
    }

    @Override
    public String getZLanguage() {
        return this.zLanguage;
    }

    @Override
    public VHtlRoomOccup setZLanguage(String zLanguage) {
        this.zLanguage = zLanguage;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VHtlRoomOccup (");

        sb.append(pkId);
        sb.append(", ").append(sRoomNum);
        sb.append(", ").append(rTentId);
        sb.append(", ").append(rFloorId);
        sb.append(", ").append(dDay);
        sb.append(", ").append(rRoomTypeId);
        sb.append(", ").append(rltOpStatus);
        sb.append(", ").append(rltCleanStatus);
        sb.append(", ").append(isLeaving);
        sb.append(", ").append(isArriving);
        sb.append(", ").append(iExceed);
        sb.append(", ").append(rHotelId);
        sb.append(", ").append(zLanguage);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IVHtlRoomOccup from) {
        setPkId(from.getPkId());
        setSRoomNum(from.getSRoomNum());
        setRTentId(from.getRTentId());
        setRFloorId(from.getRFloorId());
        setDDay(from.getDDay());
        setRRoomTypeId(from.getRRoomTypeId());
        setRltOpStatus(from.getRltOpStatus());
        setRltCleanStatus(from.getRltCleanStatus());
        setIsLeaving(from.getIsLeaving());
        setIsArriving(from.getIsArriving());
        setIExceed(from.getIExceed());
        setRHotelId(from.getRHotelId());
        setZLanguage(from.getZLanguage());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IVHtlRoomOccup> E into(E into) {
        into.from(this);
        return into;
    }

    public VHtlRoomOccup(io.vertx.core.json.JsonObject json) {
        fromJson(json);
    }
}
