/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ui.domain;


import cn.vertxup.ui.domain.tables.UiColumn;
import cn.vertxup.ui.domain.tables.UiControl;
import cn.vertxup.ui.domain.tables.UiField;
import cn.vertxup.ui.domain.tables.UiForm;
import cn.vertxup.ui.domain.tables.UiLayout;
import cn.vertxup.ui.domain.tables.UiPage;
import cn.vertxup.ui.domain.tables.records.UiColumnRecord;
import cn.vertxup.ui.domain.tables.records.UiControlRecord;
import cn.vertxup.ui.domain.tables.records.UiFieldRecord;
import cn.vertxup.ui.domain.tables.records.UiFormRecord;
import cn.vertxup.ui.domain.tables.records.UiLayoutRecord;
import cn.vertxup.ui.domain.tables.records.UiPageRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>DB_ETERNAL</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UiColumnRecord> KEY_UI_COLUMN_PRIMARY = UniqueKeys0.KEY_UI_COLUMN_PRIMARY;
    public static final UniqueKey<UiColumnRecord> KEY_UI_COLUMN_SIGMA = UniqueKeys0.KEY_UI_COLUMN_SIGMA;
    public static final UniqueKey<UiControlRecord> KEY_UI_CONTROL_PRIMARY = UniqueKeys0.KEY_UI_CONTROL_PRIMARY;
    public static final UniqueKey<UiControlRecord> KEY_UI_CONTROL_SIGN = UniqueKeys0.KEY_UI_CONTROL_SIGN;
    public static final UniqueKey<UiFieldRecord> KEY_UI_FIELD_PRIMARY = UniqueKeys0.KEY_UI_FIELD_PRIMARY;
    public static final UniqueKey<UiFieldRecord> KEY_UI_FIELD_FORM_ID = UniqueKeys0.KEY_UI_FIELD_FORM_ID;
    public static final UniqueKey<UiFormRecord> KEY_UI_FORM_PRIMARY = UniqueKeys0.KEY_UI_FORM_PRIMARY;
    public static final UniqueKey<UiFormRecord> KEY_UI_FORM_CODE = UniqueKeys0.KEY_UI_FORM_CODE;
    public static final UniqueKey<UiLayoutRecord> KEY_UI_LAYOUT_PRIMARY = UniqueKeys0.KEY_UI_LAYOUT_PRIMARY;
    public static final UniqueKey<UiLayoutRecord> KEY_UI_LAYOUT_NAME = UniqueKeys0.KEY_UI_LAYOUT_NAME;
    public static final UniqueKey<UiPageRecord> KEY_UI_PAGE_PRIMARY = UniqueKeys0.KEY_UI_PAGE_PRIMARY;
    public static final UniqueKey<UiPageRecord> KEY_UI_PAGE_APP = UniqueKeys0.KEY_UI_PAGE_APP;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<UiColumnRecord> KEY_UI_COLUMN_PRIMARY = Internal.createUniqueKey(UiColumn.UI_COLUMN, "KEY_UI_COLUMN_PRIMARY", UiColumn.UI_COLUMN.KEY);
        public static final UniqueKey<UiColumnRecord> KEY_UI_COLUMN_SIGMA = Internal.createUniqueKey(UiColumn.UI_COLUMN, "KEY_UI_COLUMN_SIGMA", UiColumn.UI_COLUMN.SIGMA, UiColumn.UI_COLUMN.CONTROL_ID, UiColumn.UI_COLUMN.DATA_INDEX);
        public static final UniqueKey<UiControlRecord> KEY_UI_CONTROL_PRIMARY = Internal.createUniqueKey(UiControl.UI_CONTROL, "KEY_UI_CONTROL_PRIMARY", UiControl.UI_CONTROL.KEY);
        public static final UniqueKey<UiControlRecord> KEY_UI_CONTROL_SIGN = Internal.createUniqueKey(UiControl.UI_CONTROL, "KEY_UI_CONTROL_SIGN", UiControl.UI_CONTROL.SIGN);
        public static final UniqueKey<UiFieldRecord> KEY_UI_FIELD_PRIMARY = Internal.createUniqueKey(UiField.UI_FIELD, "KEY_UI_FIELD_PRIMARY", UiField.UI_FIELD.KEY);
        public static final UniqueKey<UiFieldRecord> KEY_UI_FIELD_FORM_ID = Internal.createUniqueKey(UiField.UI_FIELD, "KEY_UI_FIELD_FORM_ID", UiField.UI_FIELD.FORM_ID, UiField.UI_FIELD.NAME);
        public static final UniqueKey<UiFormRecord> KEY_UI_FORM_PRIMARY = Internal.createUniqueKey(UiForm.UI_FORM, "KEY_UI_FORM_PRIMARY", UiForm.UI_FORM.KEY);
        public static final UniqueKey<UiFormRecord> KEY_UI_FORM_CODE = Internal.createUniqueKey(UiForm.UI_FORM, "KEY_UI_FORM_CODE", UiForm.UI_FORM.CODE, UiForm.UI_FORM.SIGMA);
        public static final UniqueKey<UiLayoutRecord> KEY_UI_LAYOUT_PRIMARY = Internal.createUniqueKey(UiLayout.UI_LAYOUT, "KEY_UI_LAYOUT_PRIMARY", UiLayout.UI_LAYOUT.KEY);
        public static final UniqueKey<UiLayoutRecord> KEY_UI_LAYOUT_NAME = Internal.createUniqueKey(UiLayout.UI_LAYOUT, "KEY_UI_LAYOUT_NAME", UiLayout.UI_LAYOUT.NAME, UiLayout.UI_LAYOUT.SIGMA);
        public static final UniqueKey<UiPageRecord> KEY_UI_PAGE_PRIMARY = Internal.createUniqueKey(UiPage.UI_PAGE, "KEY_UI_PAGE_PRIMARY", UiPage.UI_PAGE.KEY);
        public static final UniqueKey<UiPageRecord> KEY_UI_PAGE_APP = Internal.createUniqueKey(UiPage.UI_PAGE, "KEY_UI_PAGE_APP", UiPage.UI_PAGE.APP, UiPage.UI_PAGE.MODULE, UiPage.UI_PAGE.PAGE, UiPage.UI_PAGE.SIGMA);
    }
}
