/*
 * This up.god.file is generated by jOOQ.
 */
package com.htl.domain;


import com.htl.domain.tables.LctCity;
import com.htl.domain.tables.LctCountry;
import com.htl.domain.tables.LctDistinct;
import com.htl.domain.tables.LctFloor;
import com.htl.domain.tables.LctLocation;
import com.htl.domain.tables.LctState;
import com.htl.domain.tables.LctTent;
import com.htl.domain.tables.LctYard;
import com.htl.domain.tables.SysApp;
import com.htl.domain.tables.SysAttachment;
import com.htl.domain.tables.SysCategory;
import com.htl.domain.tables.SysMenu;
import com.htl.domain.tables.SysNumber;
import com.htl.domain.tables.SysTabular;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DbHtl extends SchemaImpl {

    /**
     * The reference instance of <code>DB_HTL</code>
     */
    public static final DbHtl DB_HTL = new DbHtl();
    private static final long serialVersionUID = -1772387752;
    /**
     * The table <code>DB_HTL.LCT_CITY</code>.
     */
    public final LctCity LCT_CITY = com.htl.domain.tables.LctCity.LCT_CITY;

    /**
     * The table <code>DB_HTL.LCT_COUNTRY</code>.
     */
    public final LctCountry LCT_COUNTRY = com.htl.domain.tables.LctCountry.LCT_COUNTRY;

    /**
     * The table <code>DB_HTL.LCT_DISTINCT</code>.
     */
    public final LctDistinct LCT_DISTINCT = com.htl.domain.tables.LctDistinct.LCT_DISTINCT;

    /**
     * The table <code>DB_HTL.LCT_FLOOR</code>.
     */
    public final LctFloor LCT_FLOOR = com.htl.domain.tables.LctFloor.LCT_FLOOR;

    /**
     * The table <code>DB_HTL.LCT_LOCATION</code>.
     */
    public final LctLocation LCT_LOCATION = com.htl.domain.tables.LctLocation.LCT_LOCATION;

    /**
     * The table <code>DB_HTL.LCT_STATE</code>.
     */
    public final LctState LCT_STATE = com.htl.domain.tables.LctState.LCT_STATE;

    /**
     * The table <code>DB_HTL.LCT_TENT</code>.
     */
    public final LctTent LCT_TENT = com.htl.domain.tables.LctTent.LCT_TENT;

    /**
     * The table <code>DB_HTL.LCT_YARD</code>.
     */
    public final LctYard LCT_YARD = com.htl.domain.tables.LctYard.LCT_YARD;

    /**
     * The table <code>DB_HTL.SYS_APP</code>.
     */
    public final SysApp SYS_APP = com.htl.domain.tables.SysApp.SYS_APP;

    /**
     * The table <code>DB_HTL.SYS_ATTACHMENT</code>.
     */
    public final SysAttachment SYS_ATTACHMENT = com.htl.domain.tables.SysAttachment.SYS_ATTACHMENT;

    /**
     * The table <code>DB_HTL.SYS_CATEGORY</code>.
     */
    public final SysCategory SYS_CATEGORY = com.htl.domain.tables.SysCategory.SYS_CATEGORY;

    /**
     * The table <code>DB_HTL.SYS_MENU</code>.
     */
    public final SysMenu SYS_MENU = com.htl.domain.tables.SysMenu.SYS_MENU;

    /**
     * The table <code>DB_HTL.SYS_NUMBER</code>.
     */
    public final SysNumber SYS_NUMBER = com.htl.domain.tables.SysNumber.SYS_NUMBER;

    /**
     * The table <code>DB_HTL.SYS_TABULAR</code>.
     */
    public final SysTabular SYS_TABULAR = com.htl.domain.tables.SysTabular.SYS_TABULAR;

    /**
     * No further instances allowed
     */
    private DbHtl() {
        super("DB_HTL", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                LctCity.LCT_CITY,
                LctCountry.LCT_COUNTRY,
                LctDistinct.LCT_DISTINCT,
                LctFloor.LCT_FLOOR,
                LctLocation.LCT_LOCATION,
                LctState.LCT_STATE,
                LctTent.LCT_TENT,
                LctYard.LCT_YARD,
                SysApp.SYS_APP,
                SysAttachment.SYS_ATTACHMENT,
                SysCategory.SYS_CATEGORY,
                SysMenu.SYS_MENU,
                SysNumber.SYS_NUMBER,
                SysTabular.SYS_TABULAR);
    }
}
