databaseChangeLog:
  # 安全表
  - include:
      file: script/sql/split/O_ACCESS_TOKEN.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/O_USER.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/S_ACTION.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/S_GROUP.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/S_PERMISSION.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/S_RESOURCE.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/S_USER.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/S_ROLE.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/S_RESOURCE_MATRIX.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/R_GROUP_ROLE.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/R_PERM_ACTION.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/R_ROLE_PERM.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/R_USER_ROLE.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/split/R_USER_GROUP.sql
      relativeToChangelogFile: false