databaseChangeLog:
  # 安全表
  - include:
      file: script/sql/schema/O_ACCESS_TOKEN.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/O_USER.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/S_ACTION.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/S_GROUP.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/S_PERMISSION.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/S_RESOURCE.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/S_USER.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/S_ROLE.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/S_RESOURCE_MATRIX.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/R_GROUP_ROLE.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/R_PERM_ACTION.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/R_ROLE_PERM.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/R_USER_ROLE.sql
      relativeToChangelogFile: false
  - include:
      file: script/sql/schema/R_USER_GROUP.sql
      relativeToChangelogFile: false