/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import up.god.jooq.tables.OthAccessToken;
import up.god.jooq.tables.interfaces.IOthAccessToken;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OthAccessTokenRecord extends UpdatableRecordImpl<OthAccessTokenRecord> implements Record14<String, byte[], byte[], byte[], Long, String, String, Boolean, String, String, String, LocalDateTime, String, LocalDateTime>, IOthAccessToken {

    private static final long serialVersionUID = 1422196179;

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.PK_ID</code>. uniqueId,PK_ID
     */
    @Override
    public OthAccessTokenRecord setPkId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.PK_ID</code>. uniqueId,PK_ID
     */
    @Override
    public String getPkId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.B_AUTH</code>. authenticate,B_AUTH
     */
    @Override
    public OthAccessTokenRecord setBAuth(byte... value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.B_AUTH</code>. authenticate,B_AUTH
     */
    @Override
    public byte[] getBAuth() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.B_REFRESH_TOKEN</code>. refreshToken,B_REFRESH_TOKEN
     */
    @Override
    public OthAccessTokenRecord setBRefreshToken(byte... value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.B_REFRESH_TOKEN</code>. refreshToken,B_REFRESH_TOKEN
     */
    @Override
    public byte[] getBRefreshToken() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.B_TOKEN</code>. token,B_TOKEN
     */
    @Override
    public OthAccessTokenRecord setBToken(byte... value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.B_TOKEN</code>. token,B_TOKEN
     */
    @Override
    public byte[] getBToken() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.L_EXPIRED_TIME</code>. expiredTime,L_EXPIRED_TIME
     */
    @Override
    public OthAccessTokenRecord setLExpiredTime(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.L_EXPIRED_TIME</code>. expiredTime,L_EXPIRED_TIME
     */
    @Override
    public Long getLExpiredTime() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.S_CODE</code>. code,S_CODE
     */
    @Override
    public OthAccessTokenRecord setSCode(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.S_CODE</code>. code,S_CODE
     */
    @Override
    public String getSCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.J_CONFIG</code>. config,J_CONFIG
     */
    @Override
    public OthAccessTokenRecord setJConfig(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.J_CONFIG</code>. config,J_CONFIG
     */
    @Override
    public String getJConfig() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    @Override
    public OthAccessTokenRecord setIsActive(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    @Override
    public Boolean getIsActive() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    @Override
    public OthAccessTokenRecord setZSigma(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    @Override
    public String getZSigma() {
        return (String) get(8);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.Z_LANGUAGE</code>. language,Z_LANGUAGE
     */
    @Override
    public OthAccessTokenRecord setZLanguage(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.Z_LANGUAGE</code>. language,Z_LANGUAGE
     */
    @Override
    public String getZLanguage() {
        return (String) get(9);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.Z_CREATE_BY</code>. createBy,Z_CREATE_BY
     */
    @Override
    public OthAccessTokenRecord setZCreateBy(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.Z_CREATE_BY</code>. createBy,Z_CREATE_BY
     */
    @Override
    public String getZCreateBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.Z_CREATE_TIME</code>. createTime,Z_CREATE_TIME
     */
    @Override
    public OthAccessTokenRecord setZCreateTime(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.Z_CREATE_TIME</code>. createTime,Z_CREATE_TIME
     */
    @Override
    public LocalDateTime getZCreateTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.Z_UPDATE_BY</code>. updateBy,Z_UPDATE_BY
     */
    @Override
    public OthAccessTokenRecord setZUpdateBy(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.Z_UPDATE_BY</code>. updateBy,Z_UPDATE_BY
     */
    @Override
    public String getZUpdateBy() {
        return (String) get(12);
    }

    /**
     * Setter for <code>DB_HTL.OTH_ACCESS_TOKEN.Z_UPDATE_TIME</code>. updateTime,Z_UPDATE_TIME
     */
    @Override
    public OthAccessTokenRecord setZUpdateTime(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_ACCESS_TOKEN.Z_UPDATE_TIME</code>. updateTime,Z_UPDATE_TIME
     */
    @Override
    public LocalDateTime getZUpdateTime() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, byte[], byte[], byte[], Long, String, String, Boolean, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, byte[], byte[], byte[], Long, String, String, Boolean, String, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return OthAccessToken.OTH_ACCESS_TOKEN.PK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field2() {
        return OthAccessToken.OTH_ACCESS_TOKEN.B_AUTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return OthAccessToken.OTH_ACCESS_TOKEN.B_REFRESH_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return OthAccessToken.OTH_ACCESS_TOKEN.B_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return OthAccessToken.OTH_ACCESS_TOKEN.L_EXPIRED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return OthAccessToken.OTH_ACCESS_TOKEN.S_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return OthAccessToken.OTH_ACCESS_TOKEN.J_CONFIG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return OthAccessToken.OTH_ACCESS_TOKEN.IS_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return OthAccessToken.OTH_ACCESS_TOKEN.Z_SIGMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return OthAccessToken.OTH_ACCESS_TOKEN.Z_LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return OthAccessToken.OTH_ACCESS_TOKEN.Z_CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field12() {
        return OthAccessToken.OTH_ACCESS_TOKEN.Z_CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return OthAccessToken.OTH_ACCESS_TOKEN.Z_UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field14() {
        return OthAccessToken.OTH_ACCESS_TOKEN.Z_UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component2() {
        return getBAuth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component3() {
        return getBRefreshToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component4() {
        return getBToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getLExpiredTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getJConfig();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getZSigma();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getZLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getZCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component12() {
        return getZCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getZUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component14() {
        return getZUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value2() {
        return getBAuth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getBRefreshToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getBToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getLExpiredTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getJConfig();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getZSigma();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getZLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getZCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value12() {
        return getZCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getZUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value14() {
        return getZUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value1(String value) {
        setPkId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value2(byte... value) {
        setBAuth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value3(byte... value) {
        setBRefreshToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value4(byte... value) {
        setBToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value5(Long value) {
        setLExpiredTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value6(String value) {
        setSCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value7(String value) {
        setJConfig(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value8(Boolean value) {
        setIsActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value9(String value) {
        setZSigma(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value10(String value) {
        setZLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value11(String value) {
        setZCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value12(LocalDateTime value) {
        setZCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value13(String value) {
        setZUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord value14(LocalDateTime value) {
        setZUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthAccessTokenRecord values(String value1, byte[] value2, byte[] value3, byte[] value4, Long value5, String value6, String value7, Boolean value8, String value9, String value10, String value11, LocalDateTime value12, String value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IOthAccessToken from) {
        setPkId(from.getPkId());
        setBAuth(from.getBAuth());
        setBRefreshToken(from.getBRefreshToken());
        setBToken(from.getBToken());
        setLExpiredTime(from.getLExpiredTime());
        setSCode(from.getSCode());
        setJConfig(from.getJConfig());
        setIsActive(from.getIsActive());
        setZSigma(from.getZSigma());
        setZLanguage(from.getZLanguage());
        setZCreateBy(from.getZCreateBy());
        setZCreateTime(from.getZCreateTime());
        setZUpdateBy(from.getZUpdateBy());
        setZUpdateTime(from.getZUpdateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IOthAccessToken> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OthAccessTokenRecord
     */
    public OthAccessTokenRecord() {
        super(OthAccessToken.OTH_ACCESS_TOKEN);
    }

    /**
     * Create a detached, initialised OthAccessTokenRecord
     */
    public OthAccessTokenRecord(String pkId, byte[] bAuth, byte[] bRefreshToken, byte[] bToken, Long lExpiredTime, String sCode, String jConfig, Boolean isActive, String zSigma, String zLanguage, String zCreateBy, LocalDateTime zCreateTime, String zUpdateBy, LocalDateTime zUpdateTime) {
        super(OthAccessToken.OTH_ACCESS_TOKEN);

        set(0, pkId);
        set(1, bAuth);
        set(2, bRefreshToken);
        set(3, bToken);
        set(4, lExpiredTime);
        set(5, sCode);
        set(6, jConfig);
        set(7, isActive);
        set(8, zSigma);
        set(9, zLanguage);
        set(10, zCreateBy);
        set(11, zCreateTime);
        set(12, zUpdateBy);
        set(13, zUpdateTime);
    }
}
