/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;

import up.god.jooq.tables.OthUser;
import up.god.jooq.tables.interfaces.IOthUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OthUserRecord extends UpdatableRecordImpl<OthUserRecord> implements Record15<String, String, String, String, String, String, String, String, Boolean, String, String, String, LocalDateTime, String, LocalDateTime>, IOthUser {

    private static final long serialVersionUID = -435538343;

    /**
     * Setter for <code>DB_HTL.OTH_USER.PK_ID</code>. uniqueId,PK_ID
     */
    @Override
    public OthUserRecord setPkId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.PK_ID</code>. uniqueId,PK_ID
     */
    @Override
    public String getPkId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.T_REDIRECT_URI</code>. redirectUri,T_REDIRECT_URI
     */
    @Override
    public OthUserRecord setTRedirectUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.T_REDIRECT_URI</code>. redirectUri,T_REDIRECT_URI
     */
    @Override
    public String getTRedirectUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.S_CODE</code>. code,S_CODE
     */
    @Override
    public OthUserRecord setSCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.S_CODE</code>. code,S_CODE
     */
    @Override
    public String getSCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.S_CLIENT_SECRET</code>. clientSecret,S_CLIENT_SECRET
     */
    @Override
    public OthUserRecord setSClientSecret(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.S_CLIENT_SECRET</code>. clientSecret,S_CLIENT_SECRET
     */
    @Override
    public String getSClientSecret() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.S_GRANT_TYPE</code>. grantType,S_GRANT_TYPE
     */
    @Override
    public OthUserRecord setSGrantType(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.S_GRANT_TYPE</code>. grantType,S_GRANT_TYPE
     */
    @Override
    public String getSGrantType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.S_SCOPE</code>. scope,S_SCOPE
     */
    @Override
    public OthUserRecord setSScope(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.S_SCOPE</code>. scope,S_SCOPE
     */
    @Override
    public String getSScope() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.J_CONFIG</code>. config,J_CONFIG
     */
    @Override
    public OthUserRecord setJConfig(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.J_CONFIG</code>. config,J_CONFIG
     */
    @Override
    public String getJConfig() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.R_CLIENT_ID</code>. clientId,R_CLIENT_ID
     */
    @Override
    public OthUserRecord setRClientId(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.R_CLIENT_ID</code>. clientId,R_CLIENT_ID
     */
    @Override
    public String getRClientId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    @Override
    public OthUserRecord setIsActive(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    @Override
    public Boolean getIsActive() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    @Override
    public OthUserRecord setZSigma(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    @Override
    public String getZSigma() {
        return (String) get(9);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.Z_LANGUAGE</code>. language,Z_LANGUAGE
     */
    @Override
    public OthUserRecord setZLanguage(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.Z_LANGUAGE</code>. language,Z_LANGUAGE
     */
    @Override
    public String getZLanguage() {
        return (String) get(10);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.Z_CREATE_BY</code>. createBy,Z_CREATE_BY
     */
    @Override
    public OthUserRecord setZCreateBy(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.Z_CREATE_BY</code>. createBy,Z_CREATE_BY
     */
    @Override
    public String getZCreateBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.Z_CREATE_TIME</code>. createTime,Z_CREATE_TIME
     */
    @Override
    public OthUserRecord setZCreateTime(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.Z_CREATE_TIME</code>. createTime,Z_CREATE_TIME
     */
    @Override
    public LocalDateTime getZCreateTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.Z_UPDATE_BY</code>. updateBy,Z_UPDATE_BY
     */
    @Override
    public OthUserRecord setZUpdateBy(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.Z_UPDATE_BY</code>. updateBy,Z_UPDATE_BY
     */
    @Override
    public String getZUpdateBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>DB_HTL.OTH_USER.Z_UPDATE_TIME</code>. updateTime,Z_UPDATE_TIME
     */
    @Override
    public OthUserRecord setZUpdateTime(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.OTH_USER.Z_UPDATE_TIME</code>. updateTime,Z_UPDATE_TIME
     */
    @Override
    public LocalDateTime getZUpdateTime() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, String, String, String, String, String, String, Boolean, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, String, String, String, String, String, String, Boolean, String, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return OthUser.OTH_USER.PK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OthUser.OTH_USER.T_REDIRECT_URI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OthUser.OTH_USER.S_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OthUser.OTH_USER.S_CLIENT_SECRET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return OthUser.OTH_USER.S_GRANT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return OthUser.OTH_USER.S_SCOPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return OthUser.OTH_USER.J_CONFIG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return OthUser.OTH_USER.R_CLIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return OthUser.OTH_USER.IS_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return OthUser.OTH_USER.Z_SIGMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return OthUser.OTH_USER.Z_LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return OthUser.OTH_USER.Z_CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return OthUser.OTH_USER.Z_CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return OthUser.OTH_USER.Z_UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field15() {
        return OthUser.OTH_USER.Z_UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTRedirectUri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSClientSecret();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSGrantType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getJConfig();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getZSigma();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getZLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getZCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component13() {
        return getZCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getZUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component15() {
        return getZUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTRedirectUri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSClientSecret();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSGrantType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getJConfig();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getZSigma();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getZLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getZCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getZCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getZUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value15() {
        return getZUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value1(String value) {
        setPkId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value2(String value) {
        setTRedirectUri(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value3(String value) {
        setSCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value4(String value) {
        setSClientSecret(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value5(String value) {
        setSGrantType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value6(String value) {
        setSScope(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value7(String value) {
        setJConfig(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value8(String value) {
        setRClientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value9(Boolean value) {
        setIsActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value10(String value) {
        setZSigma(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value11(String value) {
        setZLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value12(String value) {
        setZCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value13(LocalDateTime value) {
        setZCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value14(String value) {
        setZUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord value15(LocalDateTime value) {
        setZUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OthUserRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Boolean value9, String value10, String value11, String value12, LocalDateTime value13, String value14, LocalDateTime value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IOthUser from) {
        setPkId(from.getPkId());
        setTRedirectUri(from.getTRedirectUri());
        setSCode(from.getSCode());
        setSClientSecret(from.getSClientSecret());
        setSGrantType(from.getSGrantType());
        setSScope(from.getSScope());
        setJConfig(from.getJConfig());
        setRClientId(from.getRClientId());
        setIsActive(from.getIsActive());
        setZSigma(from.getZSigma());
        setZLanguage(from.getZLanguage());
        setZCreateBy(from.getZCreateBy());
        setZCreateTime(from.getZCreateTime());
        setZUpdateBy(from.getZUpdateBy());
        setZUpdateTime(from.getZUpdateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IOthUser> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OthUserRecord
     */
    public OthUserRecord() {
        super(OthUser.OTH_USER);
    }

    /**
     * Create a detached, initialised OthUserRecord
     */
    public OthUserRecord(String pkId, String tRedirectUri, String sCode, String sClientSecret, String sGrantType, String sScope, String jConfig, String rClientId, Boolean isActive, String zSigma, String zLanguage, String zCreateBy, LocalDateTime zCreateTime, String zUpdateBy, LocalDateTime zUpdateTime) {
        super(OthUser.OTH_USER);

        set(0, pkId);
        set(1, tRedirectUri);
        set(2, sCode);
        set(3, sClientSecret);
        set(4, sGrantType);
        set(5, sScope);
        set(6, jConfig);
        set(7, rClientId);
        set(8, isActive);
        set(9, zSigma);
        set(10, zLanguage);
        set(11, zCreateBy);
        set(12, zCreateTime);
        set(13, zUpdateBy);
        set(14, zUpdateTime);
    }
}
