/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;

import up.god.jooq.tables.VHtlCodePrice;
import up.god.jooq.tables.interfaces.IVHtlCodePrice;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VHtlCodePriceRecord extends TableRecordImpl<VHtlCodePriceRecord> implements Record13<Long, String, String, BigDecimal, BigDecimal, Long, Integer, Long, Long, Long, Boolean, Boolean, Long>, IVHtlCodePrice {

    private static final long serialVersionUID = 1295594587;

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.PK_ID</code>. uniqueId,PK_ID
     */
    @Override
    public VHtlCodePriceRecord setPkId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.PK_ID</code>. uniqueId,PK_ID
     */
    @Override
    public Long getPkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.S_CODE</code>. code,S_CODE
     */
    @Override
    public VHtlCodePriceRecord setSCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.S_CODE</code>. code,S_CODE
     */
    @Override
    public String getSCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.S_NAME</code>. 【房价码名称】,name,S_NAME
     */
    @Override
    public VHtlCodePriceRecord setSName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.S_NAME</code>. 【房价码名称】,name,S_NAME
     */
    @Override
    public String getSName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.D_PRICE</code>. 【挂牌价】当前房价码对应挂牌价,price,D_PRICE
     */
    @Override
    public VHtlCodePriceRecord setDPrice(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.D_PRICE</code>. 【挂牌价】当前房价码对应挂牌价,price,D_PRICE
     */
    @Override
    public BigDecimal getDPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.D_BK_PRICE</code>. 【早餐价】当前房价码对应早餐价：包早价 = price + brekkerPrice,brekkerPrice,D_BK_PRICE
     */
    @Override
    public VHtlCodePriceRecord setDBkPrice(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.D_BK_PRICE</code>. 【早餐价】当前房价码对应早餐价：包早价 = price + brekkerPrice,brekkerPrice,D_BK_PRICE
     */
    @Override
    public BigDecimal getDBkPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.R_ROOM_TYPE_ID</code>. 【房型信息】该房价码对应的房型信息,roomTypeId,R_ROOM_TYPE_ID
     */
    @Override
    public VHtlCodePriceRecord setRRoomTypeId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.R_ROOM_TYPE_ID</code>. 【房型信息】该房价码对应的房型信息,roomTypeId,R_ROOM_TYPE_ID
     */
    @Override
    public Long getRRoomTypeId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.I_ORDER</code>. order,I_ORDER
     */
    @Override
    public VHtlCodePriceRecord setIOrder(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.I_ORDER</code>. order,I_ORDER
     */
    @Override
    public Integer getIOrder() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.RLT_PRICECAT</code>. REF: SYS_TABULAR【价格类型】房价码对应价格类型,priceCat,RLT_PRICECAT
     */
    @Override
    public VHtlCodePriceRecord setRltPricecat(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.RLT_PRICECAT</code>. REF: SYS_TABULAR【价格类型】房价码对应价格类型,priceCat,RLT_PRICECAT
     */
    @Override
    public Long getRltPricecat() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.RLT_SOURCE</code>. REF: SYS_TABULAR【来源码】该房价码关联来源码,source,RLT_SOURCE
     */
    @Override
    public VHtlCodePriceRecord setRltSource(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.RLT_SOURCE</code>. REF: SYS_TABULAR【来源码】该房价码关联来源码,source,RLT_SOURCE
     */
    @Override
    public Long getRltSource() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.RLT_MARKET</code>. REF: SYS_TABULAR【市场码】该房价码关联市场码,market,RLT_MARKET
     */
    @Override
    public VHtlCodePriceRecord setRltMarket(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.RLT_MARKET</code>. REF: SYS_TABULAR【市场码】该房价码关联市场码,market,RLT_MARKET
     */
    @Override
    public Long getRltMarket() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.IS_HASBREK</code>. 房包早？,hasBrek,IS_HASBREK
     */
    @Override
    public VHtlCodePriceRecord setIsHasbrek(Boolean value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.IS_HASBREK</code>. 房包早？,hasBrek,IS_HASBREK
     */
    @Override
    public Boolean getIsHasbrek() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    @Override
    public VHtlCodePriceRecord setIsActive(Boolean value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    @Override
    public Boolean getIsActive() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_code_price.R_HOTEL_ID</code>. hotelId,R_HOTEL_ID
     */
    @Override
    public VHtlCodePriceRecord setRHotelId(Long value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_code_price.R_HOTEL_ID</code>. hotelId,R_HOTEL_ID
     */
    @Override
    public Long getRHotelId() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, BigDecimal, BigDecimal, Long, Integer, Long, Long, Long, Boolean, Boolean, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, BigDecimal, BigDecimal, Long, Integer, Long, Long, Long, Boolean, Boolean, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.PK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.S_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.S_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.D_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.D_BK_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.R_ROOM_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.I_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.RLT_PRICECAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.RLT_SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.RLT_MARKET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.IS_HASBREK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.IS_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return VHtlCodePrice.V_HTL_CODE_PRICE.R_HOTEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getPkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getDPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getDBkPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getRRoomTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getIOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getRltPricecat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getRltSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getRltMarket();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component11() {
        return getIsHasbrek();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component13() {
        return getRHotelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getDPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getDBkPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getRRoomTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getRltPricecat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getRltSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getRltMarket();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getIsHasbrek();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getRHotelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value1(Long value) {
        setPkId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value2(String value) {
        setSCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value3(String value) {
        setSName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value4(BigDecimal value) {
        setDPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value5(BigDecimal value) {
        setDBkPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value6(Long value) {
        setRRoomTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value7(Integer value) {
        setIOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value8(Long value) {
        setRltPricecat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value9(Long value) {
        setRltSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value10(Long value) {
        setRltMarket(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value11(Boolean value) {
        setIsHasbrek(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value12(Boolean value) {
        setIsActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord value13(Long value) {
        setRHotelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlCodePriceRecord values(Long value1, String value2, String value3, BigDecimal value4, BigDecimal value5, Long value6, Integer value7, Long value8, Long value9, Long value10, Boolean value11, Boolean value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IVHtlCodePrice from) {
        setPkId(from.getPkId());
        setSCode(from.getSCode());
        setSName(from.getSName());
        setDPrice(from.getDPrice());
        setDBkPrice(from.getDBkPrice());
        setRRoomTypeId(from.getRRoomTypeId());
        setIOrder(from.getIOrder());
        setRltPricecat(from.getRltPricecat());
        setRltSource(from.getRltSource());
        setRltMarket(from.getRltMarket());
        setIsHasbrek(from.getIsHasbrek());
        setIsActive(from.getIsActive());
        setRHotelId(from.getRHotelId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IVHtlCodePrice> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VHtlCodePriceRecord
     */
    public VHtlCodePriceRecord() {
        super(VHtlCodePrice.V_HTL_CODE_PRICE);
    }

    /**
     * Create a detached, initialised VHtlCodePriceRecord
     */
    public VHtlCodePriceRecord(Long pkId, String sCode, String sName, BigDecimal dPrice, BigDecimal dBkPrice, Long rRoomTypeId, Integer iOrder, Long rltPricecat, Long rltSource, Long rltMarket, Boolean isHasbrek, Boolean isActive, Long rHotelId) {
        super(VHtlCodePrice.V_HTL_CODE_PRICE);

        set(0, pkId);
        set(1, sCode);
        set(2, sName);
        set(3, dPrice);
        set(4, dBkPrice);
        set(5, rRoomTypeId);
        set(6, iOrder);
        set(7, rltPricecat);
        set(8, rltSource);
        set(9, rltMarket);
        set(10, isHasbrek);
        set(11, isActive);
        set(12, rHotelId);
    }
}
