/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.TableRecordImpl;

import up.god.jooq.tables.VHtlRoomToday;
import up.god.jooq.tables.interfaces.IVHtlRoomToday;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VHtlRoomTodayRecord extends TableRecordImpl<VHtlRoomTodayRecord> implements Record17<Long, Long, String, String, Long, Long, LocalDate, Long, Long, Long, Boolean, Boolean, Boolean, Long, String, LocalDateTime, LocalDateTime>, IVHtlRoomToday {

    private static final long serialVersionUID = 621937502;

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.PK_ID</code>. uniqueId,PK_ID
     */
    @Override
    public VHtlRoomTodayRecord setPkId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.PK_ID</code>. uniqueId,PK_ID
     */
    @Override
    public Long getPkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.S_STATUS_ID</code>. uniqueId,PK_ID
     */
    @Override
    public VHtlRoomTodayRecord setSStatusId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.S_STATUS_ID</code>. uniqueId,PK_ID
     */
    @Override
    public Long getSStatusId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.S_ROOM_NUM</code>. number,S_ROOM_NUM
     */
    @Override
    public VHtlRoomTodayRecord setSRoomNum(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.S_ROOM_NUM</code>. number,S_ROOM_NUM
     */
    @Override
    public String getSRoomNum() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    @Override
    public VHtlRoomTodayRecord setZSigma(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    @Override
    public String getZSigma() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.R_TENT_ID</code>. tent,R_TENT_ID
     */
    @Override
    public VHtlRoomTodayRecord setRTentId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.R_TENT_ID</code>. tent,R_TENT_ID
     */
    @Override
    public Long getRTentId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.R_FLOOR_ID</code>. floor,R_FLOOR_ID
     */
    @Override
    public VHtlRoomTodayRecord setRFloorId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.R_FLOOR_ID</code>. floor,R_FLOOR_ID
     */
    @Override
    public Long getRFloorId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.D_DAY</code>. day,D_DAY
     */
    @Override
    public VHtlRoomTodayRecord setDDay(LocalDate value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.D_DAY</code>. day,D_DAY
     */
    @Override
    public LocalDate getDDay() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.R_ROOM_TYPE_ID</code>. roomTypeId,R_ROOM_TYPE_ID
     */
    @Override
    public VHtlRoomTodayRecord setRRoomTypeId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.R_ROOM_TYPE_ID</code>. roomTypeId,R_ROOM_TYPE_ID
     */
    @Override
    public Long getRRoomTypeId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.RLT_OP_STATUS</code>. 操作状态：可操作（空、占用、预离、预抵）、维修、预留、停用、自用,opStatus,RLT_OP_STATUS
     */
    @Override
    public VHtlRoomTodayRecord setRltOpStatus(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.RLT_OP_STATUS</code>. 操作状态：可操作（空、占用、预离、预抵）、维修、预留、停用、自用,opStatus,RLT_OP_STATUS
     */
    @Override
    public Long getRltOpStatus() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.RLT_CLEAN_STATUS</code>. 清洁状态,cleanStatus,RLT_CLEAN_STATUS
     */
    @Override
    public VHtlRoomTodayRecord setRltCleanStatus(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.RLT_CLEAN_STATUS</code>. 清洁状态,cleanStatus,RLT_CLEAN_STATUS
     */
    @Override
    public Long getRltCleanStatus() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.IS_LEAVING</code>. 是否预离,leaving,IS_LEAVING
     */
    @Override
    public VHtlRoomTodayRecord setIsLeaving(Boolean value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.IS_LEAVING</code>. 是否预离,leaving,IS_LEAVING
     */
    @Override
    public Boolean getIsLeaving() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    @Override
    public VHtlRoomTodayRecord setIsActive(Boolean value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    @Override
    public Boolean getIsActive() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.IS_ARRIVING</code>. 是否预抵,arriving,IS_ARRIVING
     */
    @Override
    public VHtlRoomTodayRecord setIsArriving(Boolean value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.IS_ARRIVING</code>. 是否预抵,arriving,IS_ARRIVING
     */
    @Override
    public Boolean getIsArriving() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.R_HOTEL_ID</code>. hotelId,R_HOTEL_ID
     */
    @Override
    public VHtlRoomTodayRecord setRHotelId(Long value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.R_HOTEL_ID</code>. hotelId,R_HOTEL_ID
     */
    @Override
    public Long getRHotelId() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.Z_LANGUAGE</code>. language,Z_LANGUAGE
     */
    @Override
    public VHtlRoomTodayRecord setZLanguage(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.Z_LANGUAGE</code>. language,Z_LANGUAGE
     */
    @Override
    public String getZLanguage() {
        return (String) get(14);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.Z_CREATE_TIME</code>. createTime,Z_CREATE_TIME
     */
    @Override
    public VHtlRoomTodayRecord setZCreateTime(LocalDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.Z_CREATE_TIME</code>. createTime,Z_CREATE_TIME
     */
    @Override
    public LocalDateTime getZCreateTime() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>DB_HTL.v_htl_room_today.Z_UPDATE_TIME</code>. updateTime,Z_UPDATE_TIME
     */
    @Override
    public VHtlRoomTodayRecord setZUpdateTime(LocalDateTime value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_htl_room_today.Z_UPDATE_TIME</code>. updateTime,Z_UPDATE_TIME
     */
    @Override
    public LocalDateTime getZUpdateTime() {
        return (LocalDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, Long, String, String, Long, Long, LocalDate, Long, Long, Long, Boolean, Boolean, Boolean, Long, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, Long, String, String, Long, Long, LocalDate, Long, Long, Long, Boolean, Boolean, Boolean, Long, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.PK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.S_STATUS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.S_ROOM_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.Z_SIGMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.R_TENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.R_FLOOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field7() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.D_DAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.R_ROOM_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.RLT_OP_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.RLT_CLEAN_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.IS_LEAVING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.IS_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.IS_ARRIVING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.R_HOTEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.Z_LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field16() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.Z_CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field17() {
        return VHtlRoomToday.V_HTL_ROOM_TODAY.Z_UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getPkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getSStatusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSRoomNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getZSigma();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getRTentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getRFloorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component7() {
        return getDDay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getRRoomTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getRltOpStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getRltCleanStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component11() {
        return getIsLeaving();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component13() {
        return getIsArriving();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component14() {
        return getRHotelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getZLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component16() {
        return getZCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component17() {
        return getZUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getSStatusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSRoomNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getZSigma();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getRTentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getRFloorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value7() {
        return getDDay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getRRoomTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getRltOpStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getRltCleanStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getIsLeaving();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getIsArriving();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getRHotelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getZLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value16() {
        return getZCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value17() {
        return getZUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value1(Long value) {
        setPkId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value2(Long value) {
        setSStatusId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value3(String value) {
        setSRoomNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value4(String value) {
        setZSigma(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value5(Long value) {
        setRTentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value6(Long value) {
        setRFloorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value7(LocalDate value) {
        setDDay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value8(Long value) {
        setRRoomTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value9(Long value) {
        setRltOpStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value10(Long value) {
        setRltCleanStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value11(Boolean value) {
        setIsLeaving(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value12(Boolean value) {
        setIsActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value13(Boolean value) {
        setIsArriving(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value14(Long value) {
        setRHotelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value15(String value) {
        setZLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value16(LocalDateTime value) {
        setZCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord value17(LocalDateTime value) {
        setZUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VHtlRoomTodayRecord values(Long value1, Long value2, String value3, String value4, Long value5, Long value6, LocalDate value7, Long value8, Long value9, Long value10, Boolean value11, Boolean value12, Boolean value13, Long value14, String value15, LocalDateTime value16, LocalDateTime value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IVHtlRoomToday from) {
        setPkId(from.getPkId());
        setSStatusId(from.getSStatusId());
        setSRoomNum(from.getSRoomNum());
        setZSigma(from.getZSigma());
        setRTentId(from.getRTentId());
        setRFloorId(from.getRFloorId());
        setDDay(from.getDDay());
        setRRoomTypeId(from.getRRoomTypeId());
        setRltOpStatus(from.getRltOpStatus());
        setRltCleanStatus(from.getRltCleanStatus());
        setIsLeaving(from.getIsLeaving());
        setIsActive(from.getIsActive());
        setIsArriving(from.getIsArriving());
        setRHotelId(from.getRHotelId());
        setZLanguage(from.getZLanguage());
        setZCreateTime(from.getZCreateTime());
        setZUpdateTime(from.getZUpdateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IVHtlRoomToday> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VHtlRoomTodayRecord
     */
    public VHtlRoomTodayRecord() {
        super(VHtlRoomToday.V_HTL_ROOM_TODAY);
    }

    /**
     * Create a detached, initialised VHtlRoomTodayRecord
     */
    public VHtlRoomTodayRecord(Long pkId, Long sStatusId, String sRoomNum, String zSigma, Long rTentId, Long rFloorId, LocalDate dDay, Long rRoomTypeId, Long rltOpStatus, Long rltCleanStatus, Boolean isLeaving, Boolean isActive, Boolean isArriving, Long rHotelId, String zLanguage, LocalDateTime zCreateTime, LocalDateTime zUpdateTime) {
        super(VHtlRoomToday.V_HTL_ROOM_TODAY);

        set(0, pkId);
        set(1, sStatusId);
        set(2, sRoomNum);
        set(3, zSigma);
        set(4, rTentId);
        set(5, rFloorId);
        set(6, dDay);
        set(7, rRoomTypeId);
        set(8, rltOpStatus);
        set(9, rltCleanStatus);
        set(10, isLeaving);
        set(11, isActive);
        set(12, isArriving);
        set(13, rHotelId);
        set(14, zLanguage);
        set(15, zCreateTime);
        set(16, zUpdateTime);
    }
}
