/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;

import up.god.jooq.tables.VSecUserRoles;
import up.god.jooq.tables.interfaces.IVSecUserRoles;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VSecUserRolesRecord extends TableRecordImpl<VSecUserRolesRecord> implements Record5<String, String, String, String, String>, IVSecUserRoles {

    private static final long serialVersionUID = 292167023;

    /**
     * Setter for <code>DB_HTL.v_sec_user_roles.R_USER_ID</code>. userId,R_USER_ID
     */
    @Override
    public VSecUserRolesRecord setRUserId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_sec_user_roles.R_USER_ID</code>. userId,R_USER_ID
     */
    @Override
    public String getRUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DB_HTL.v_sec_user_roles.S_USERNAME</code>. 登陆账号,username,S_USERNAME
     */
    @Override
    public VSecUserRolesRecord setSUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_sec_user_roles.S_USERNAME</code>. 登陆账号,username,S_USERNAME
     */
    @Override
    public String getSUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DB_HTL.v_sec_user_roles.R_ROLE_ID</code>. roleId,R_ROLE_ID
     */
    @Override
    public VSecUserRolesRecord setRRoleId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_sec_user_roles.R_ROLE_ID</code>. roleId,R_ROLE_ID
     */
    @Override
    public String getRRoleId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DB_HTL.v_sec_user_roles.S_NAME</code>. 角色名称,name,S_NAME
     */
    @Override
    public VSecUserRolesRecord setSName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_sec_user_roles.S_NAME</code>. 角色名称,name,S_NAME
     */
    @Override
    public String getSName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DB_HTL.v_sec_user_roles.S_CODE</code>. code,S_CODE
     */
    @Override
    public VSecUserRolesRecord setSCode(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>DB_HTL.v_sec_user_roles.S_CODE</code>. code,S_CODE
     */
    @Override
    public String getSCode() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return VSecUserRoles.V_SEC_USER_ROLES.R_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VSecUserRoles.V_SEC_USER_ROLES.S_USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VSecUserRoles.V_SEC_USER_ROLES.R_ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VSecUserRoles.V_SEC_USER_ROLES.S_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VSecUserRoles.V_SEC_USER_ROLES.S_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSecUserRolesRecord value1(String value) {
        setRUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSecUserRolesRecord value2(String value) {
        setSUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSecUserRolesRecord value3(String value) {
        setRRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSecUserRolesRecord value4(String value) {
        setSName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSecUserRolesRecord value5(String value) {
        setSCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VSecUserRolesRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IVSecUserRoles from) {
        setRUserId(from.getRUserId());
        setSUsername(from.getSUsername());
        setRRoleId(from.getRRoleId());
        setSName(from.getSName());
        setSCode(from.getSCode());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IVSecUserRoles> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VSecUserRolesRecord
     */
    public VSecUserRolesRecord() {
        super(VSecUserRoles.V_SEC_USER_ROLES);
    }

    /**
     * Create a detached, initialised VSecUserRolesRecord
     */
    public VSecUserRolesRecord(String rUserId, String sUsername, String rRoleId, String sName, String sCode) {
        super(VSecUserRoles.V_SEC_USER_ROLES);

        set(0, rUserId);
        set(1, sUsername);
        set(2, rRoleId);
        set(3, sName);
        set(4, sCode);
    }
}
