/*
 * This up.god.file is generated by jOOQ.
 */
package com.htl.domain.tables.daos;


import com.htl.domain.tables.LctLocation;
import com.htl.domain.tables.records.LctLocationRecord;

import io.github.jklingsporn.vertx.jooq.future.VertxDAO;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


import java.util.concurrent.CompletableFuture;

import io.github.jklingsporn.vertx.jooq.future.util.FutureTool;

/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LctLocationDao extends DAOImpl<LctLocationRecord, com.htl.domain.tables.pojos.LctLocation, String> implements VertxDAO<com.htl.domain.tables.records.LctLocationRecord, com.htl.domain.tables.pojos.LctLocation, java.lang.String> {

    private io.vertx.core.Vertx vertx;

    /**
     * Create a new LctLocationDao without any configuration
     */
    public LctLocationDao() {
        super(LctLocation.LCT_LOCATION, com.htl.domain.tables.pojos.LctLocation.class);
    }

    /**
     * Create a new LctLocationDao with an attached configuration
     */
    public LctLocationDao(Configuration configuration) {
        super(LctLocation.LCT_LOCATION, com.htl.domain.tables.pojos.LctLocation.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.htl.domain.tables.pojos.LctLocation object) {
        return object.getPkId();
    }

    /**
     * Fetch records that have <code>PK_ID IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchByPkId(String... values) {
        return fetch(LctLocation.LCT_LOCATION.PK_ID, values);
    }

    /**
     * Fetch a unique record that has <code>PK_ID = value</code>
     */
    public com.htl.domain.tables.pojos.LctLocation fetchOneByPkId(String value) {
        return fetchOne(LctLocation.LCT_LOCATION.PK_ID, value);
    }

    /**
     * Fetch records that have <code>S_NAME IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchBySName(String... values) {
        return fetch(LctLocation.LCT_LOCATION.S_NAME, values);
    }

    /**
     * Fetch records that have <code>S_CODE IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchBySCode(String... values) {
        return fetch(LctLocation.LCT_LOCATION.S_CODE, values);
    }

    /**
     * Fetch records that have <code>S_ADDRESS IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchBySAddress(String... values) {
        return fetch(LctLocation.LCT_LOCATION.S_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>S_CITY IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchBySCity(String... values) {
        return fetch(LctLocation.LCT_LOCATION.S_CITY, values);
    }

    /**
     * Fetch records that have <code>S_COUNTRY IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchBySCountry(String... values) {
        return fetch(LctLocation.LCT_LOCATION.S_COUNTRY, values);
    }

    /**
     * Fetch records that have <code>S_DISTINCT IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchBySDistinct(String... values) {
        return fetch(LctLocation.LCT_LOCATION.S_DISTINCT, values);
    }

    /**
     * Fetch records that have <code>S_FULLNAME IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchBySFullname(String... values) {
        return fetch(LctLocation.LCT_LOCATION.S_FULLNAME, values);
    }

    /**
     * Fetch records that have <code>S_STATE IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchBySState(String... values) {
        return fetch(LctLocation.LCT_LOCATION.S_STATE, values);
    }

    /**
     * Fetch records that have <code>S_STREET1 IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchBySStreet1(String... values) {
        return fetch(LctLocation.LCT_LOCATION.S_STREET1, values);
    }

    /**
     * Fetch records that have <code>S_STREET2 IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchBySStreet2(String... values) {
        return fetch(LctLocation.LCT_LOCATION.S_STREET2, values);
    }

    /**
     * Fetch records that have <code>S_STREET3 IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchBySStreet3(String... values) {
        return fetch(LctLocation.LCT_LOCATION.S_STREET3, values);
    }

    /**
     * Fetch records that have <code>S_ZIP IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchBySZip(String... values) {
        return fetch(LctLocation.LCT_LOCATION.S_ZIP, values);
    }

    /**
     * Fetch records that have <code>J_CONFIG IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchByJConfig(String... values) {
        return fetch(LctLocation.LCT_LOCATION.J_CONFIG, values);
    }

    /**
     * Fetch records that have <code>R_DISTINCT_ID IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchByRDistinctId(String... values) {
        return fetch(LctLocation.LCT_LOCATION.R_DISTINCT_ID, values);
    }

    /**
     * Fetch records that have <code>IS_ACTIVE IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchByIsActive(Boolean... values) {
        return fetch(LctLocation.LCT_LOCATION.IS_ACTIVE, values);
    }

    /**
     * Fetch records that have <code>Z_SIGMA IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchByZSigma(String... values) {
        return fetch(LctLocation.LCT_LOCATION.Z_SIGMA, values);
    }

    /**
     * Fetch records that have <code>Z_LANGUAGE IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchByZLanguage(String... values) {
        return fetch(LctLocation.LCT_LOCATION.Z_LANGUAGE, values);
    }

    /**
     * Fetch records that have <code>Z_CREATE_BY IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchByZCreateBy(String... values) {
        return fetch(LctLocation.LCT_LOCATION.Z_CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>Z_CREATE_TIME IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchByZCreateTime(LocalDateTime... values) {
        return fetch(LctLocation.LCT_LOCATION.Z_CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>Z_UPDATE_BY IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchByZUpdateBy(String... values) {
        return fetch(LctLocation.LCT_LOCATION.Z_UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>Z_UPDATE_TIME IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.LctLocation> fetchByZUpdateTime(LocalDateTime... values) {
        return fetch(LctLocation.LCT_LOCATION.Z_UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>PK_ID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchByPkIdAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.PK_ID, values);
    }

    /**
     * Fetch a unique record that has <code>PK_ID = value</code> asynchronously
     */
    public CompletableFuture<com.htl.domain.tables.pojos.LctLocation> fetchOneByPkIdAsync(String value) {
        return FutureTool.executeBlocking(h -> h.complete(fetchOneByPkId(value)), vertx());
    }

    /**
     * Fetch records that have <code>S_NAME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchBySNameAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.S_NAME, values);
    }

    /**
     * Fetch records that have <code>S_CODE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchBySCodeAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.S_CODE, values);
    }

    /**
     * Fetch records that have <code>S_ADDRESS IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchBySAddressAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.S_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>S_CITY IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchBySCityAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.S_CITY, values);
    }

    /**
     * Fetch records that have <code>S_COUNTRY IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchBySCountryAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.S_COUNTRY, values);
    }

    /**
     * Fetch records that have <code>S_DISTINCT IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchBySDistinctAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.S_DISTINCT, values);
    }

    /**
     * Fetch records that have <code>S_FULLNAME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchBySFullnameAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.S_FULLNAME, values);
    }

    /**
     * Fetch records that have <code>S_STATE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchBySStateAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.S_STATE, values);
    }

    /**
     * Fetch records that have <code>S_STREET1 IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchBySStreet1Async(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.S_STREET1, values);
    }

    /**
     * Fetch records that have <code>S_STREET2 IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchBySStreet2Async(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.S_STREET2, values);
    }

    /**
     * Fetch records that have <code>S_STREET3 IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchBySStreet3Async(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.S_STREET3, values);
    }

    /**
     * Fetch records that have <code>S_ZIP IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchBySZipAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.S_ZIP, values);
    }

    /**
     * Fetch records that have <code>J_CONFIG IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchByJConfigAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.J_CONFIG, values);
    }

    /**
     * Fetch records that have <code>R_DISTINCT_ID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchByRDistinctIdAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.R_DISTINCT_ID, values);
    }

    /**
     * Fetch records that have <code>IS_ACTIVE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchByIsActiveAsync(List<Boolean> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.IS_ACTIVE, values);
    }

    /**
     * Fetch records that have <code>Z_SIGMA IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchByZSigmaAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.Z_SIGMA, values);
    }

    /**
     * Fetch records that have <code>Z_LANGUAGE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchByZLanguageAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.Z_LANGUAGE, values);
    }

    /**
     * Fetch records that have <code>Z_CREATE_BY IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchByZCreateByAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.Z_CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>Z_CREATE_TIME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchByZCreateTimeAsync(List<LocalDateTime> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.Z_CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>Z_UPDATE_BY IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchByZUpdateByAsync(List<String> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.Z_UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>Z_UPDATE_TIME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.LctLocation>> fetchByZUpdateTimeAsync(List<LocalDateTime> values) {
        return fetchAsync(LctLocation.LCT_LOCATION.Z_UPDATE_TIME, values);
    }

    @Override
    public void setVertx(io.vertx.core.Vertx vertx) {
        this.vertx = vertx;
    }

    @Override
    public io.vertx.core.Vertx vertx() {
        return this.vertx;
    }

}
