/*
 * This up.god.file is generated by jOOQ.
 */
package com.htl.domain.tables.daos;


import com.htl.domain.tables.SysCategory;
import com.htl.domain.tables.records.SysCategoryRecord;

import io.github.jklingsporn.vertx.jooq.future.VertxDAO;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


import java.util.concurrent.CompletableFuture;

import io.github.jklingsporn.vertx.jooq.future.util.FutureTool;

/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SysCategoryDao extends DAOImpl<SysCategoryRecord, com.htl.domain.tables.pojos.SysCategory, String> implements VertxDAO<com.htl.domain.tables.records.SysCategoryRecord, com.htl.domain.tables.pojos.SysCategory, java.lang.String> {

    private io.vertx.core.Vertx vertx;

    /**
     * Create a new SysCategoryDao without any configuration
     */
    public SysCategoryDao() {
        super(SysCategory.SYS_CATEGORY, com.htl.domain.tables.pojos.SysCategory.class);
    }

    /**
     * Create a new SysCategoryDao with an attached configuration
     */
    public SysCategoryDao(Configuration configuration) {
        super(SysCategory.SYS_CATEGORY, com.htl.domain.tables.pojos.SysCategory.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.htl.domain.tables.pojos.SysCategory object) {
        return object.getPkId();
    }

    /**
     * Fetch records that have <code>PK_ID IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByPkId(String... values) {
        return fetch(SysCategory.SYS_CATEGORY.PK_ID, values);
    }

    /**
     * Fetch a unique record that has <code>PK_ID = value</code>
     */
    public com.htl.domain.tables.pojos.SysCategory fetchOneByPkId(String value) {
        return fetchOne(SysCategory.SYS_CATEGORY.PK_ID, value);
    }

    /**
     * Fetch records that have <code>S_NAME IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchBySName(String... values) {
        return fetch(SysCategory.SYS_CATEGORY.S_NAME, values);
    }

    /**
     * Fetch records that have <code>S_CODE IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchBySCode(String... values) {
        return fetch(SysCategory.SYS_CATEGORY.S_CODE, values);
    }

    /**
     * Fetch records that have <code>S_TYPE IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchBySType(String... values) {
        return fetch(SysCategory.SYS_CATEGORY.S_TYPE, values);
    }

    /**
     * Fetch records that have <code>J_CONFIG IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByJConfig(String... values) {
        return fetch(SysCategory.SYS_CATEGORY.J_CONFIG, values);
    }

    /**
     * Fetch records that have <code>I_LEFT IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByILeft(Long... values) {
        return fetch(SysCategory.SYS_CATEGORY.I_LEFT, values);
    }

    /**
     * Fetch records that have <code>I_LEVEL IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByILevel(Integer... values) {
        return fetch(SysCategory.SYS_CATEGORY.I_LEVEL, values);
    }

    /**
     * Fetch records that have <code>I_RIGHT IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByIRight(Long... values) {
        return fetch(SysCategory.SYS_CATEGORY.I_RIGHT, values);
    }

    /**
     * Fetch records that have <code>R_PARENT_ID IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByRParentId(String... values) {
        return fetch(SysCategory.SYS_CATEGORY.R_PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>IS_ACTIVE IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByIsActive(Boolean... values) {
        return fetch(SysCategory.SYS_CATEGORY.IS_ACTIVE, values);
    }

    /**
     * Fetch records that have <code>Z_SIGMA IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByZSigma(String... values) {
        return fetch(SysCategory.SYS_CATEGORY.Z_SIGMA, values);
    }

    /**
     * Fetch records that have <code>Z_LANGUAGE IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByZLanguage(String... values) {
        return fetch(SysCategory.SYS_CATEGORY.Z_LANGUAGE, values);
    }

    /**
     * Fetch records that have <code>Z_CREATE_BY IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByZCreateBy(String... values) {
        return fetch(SysCategory.SYS_CATEGORY.Z_CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>Z_CREATE_TIME IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByZCreateTime(LocalDateTime... values) {
        return fetch(SysCategory.SYS_CATEGORY.Z_CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>Z_UPDATE_BY IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByZUpdateBy(String... values) {
        return fetch(SysCategory.SYS_CATEGORY.Z_UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>Z_UPDATE_TIME IN (values)</code>
     */
    public List<com.htl.domain.tables.pojos.SysCategory> fetchByZUpdateTime(LocalDateTime... values) {
        return fetch(SysCategory.SYS_CATEGORY.Z_UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>PK_ID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByPkIdAsync(List<String> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.PK_ID, values);
    }

    /**
     * Fetch a unique record that has <code>PK_ID = value</code> asynchronously
     */
    public CompletableFuture<com.htl.domain.tables.pojos.SysCategory> fetchOneByPkIdAsync(String value) {
        return FutureTool.executeBlocking(h -> h.complete(fetchOneByPkId(value)), vertx());
    }

    /**
     * Fetch records that have <code>S_NAME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchBySNameAsync(List<String> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.S_NAME, values);
    }

    /**
     * Fetch records that have <code>S_CODE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchBySCodeAsync(List<String> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.S_CODE, values);
    }

    /**
     * Fetch records that have <code>S_TYPE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchBySTypeAsync(List<String> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.S_TYPE, values);
    }

    /**
     * Fetch records that have <code>J_CONFIG IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByJConfigAsync(List<String> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.J_CONFIG, values);
    }

    /**
     * Fetch records that have <code>I_LEFT IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByILeftAsync(List<Long> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.I_LEFT, values);
    }

    /**
     * Fetch records that have <code>I_LEVEL IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByILevelAsync(List<Integer> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.I_LEVEL, values);
    }

    /**
     * Fetch records that have <code>I_RIGHT IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByIRightAsync(List<Long> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.I_RIGHT, values);
    }

    /**
     * Fetch records that have <code>R_PARENT_ID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByRParentIdAsync(List<String> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.R_PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>IS_ACTIVE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByIsActiveAsync(List<Boolean> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.IS_ACTIVE, values);
    }

    /**
     * Fetch records that have <code>Z_SIGMA IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByZSigmaAsync(List<String> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.Z_SIGMA, values);
    }

    /**
     * Fetch records that have <code>Z_LANGUAGE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByZLanguageAsync(List<String> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.Z_LANGUAGE, values);
    }

    /**
     * Fetch records that have <code>Z_CREATE_BY IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByZCreateByAsync(List<String> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.Z_CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>Z_CREATE_TIME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByZCreateTimeAsync(List<LocalDateTime> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.Z_CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>Z_UPDATE_BY IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByZUpdateByAsync(List<String> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.Z_UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>Z_UPDATE_TIME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<com.htl.domain.tables.pojos.SysCategory>> fetchByZUpdateTimeAsync(List<LocalDateTime> values) {
        return fetchAsync(SysCategory.SYS_CATEGORY.Z_UPDATE_TIME, values);
    }

    @Override
    public void setVertx(io.vertx.core.Vertx vertx) {
        this.vertx = vertx;
    }

    @Override
    public io.vertx.core.Vertx vertx() {
        return this.vertx;
    }

}
