/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.daos;


import io.github.jklingsporn.vertx.jooq.future.VertxDAO;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import up.god.jooq.tables.ResHisDeposit;
import up.god.jooq.tables.records.ResHisDepositRecord;


import java.util.concurrent.CompletableFuture;
import io.github.jklingsporn.vertx.jooq.future.util.FutureTool;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResHisDepositDao extends DAOImpl<ResHisDepositRecord, up.god.jooq.tables.pojos.ResHisDeposit, String> implements VertxDAO<up.god.jooq.tables.records.ResHisDepositRecord,up.god.jooq.tables.pojos.ResHisDeposit,java.lang.String> {

    /**
     * Create a new ResHisDepositDao without any configuration
     */
    public ResHisDepositDao() {
        super(ResHisDeposit.RES_HIS_DEPOSIT, up.god.jooq.tables.pojos.ResHisDeposit.class);
    }

    /**
     * Create a new ResHisDepositDao with an attached configuration
     */
    public ResHisDepositDao(Configuration configuration) {
        super(ResHisDeposit.RES_HIS_DEPOSIT, up.god.jooq.tables.pojos.ResHisDeposit.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(up.god.jooq.tables.pojos.ResHisDeposit object) {
        return object.getPkId();
    }

    /**
     * Fetch records that have <code>PK_ID IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByPkId(String... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.PK_ID, values);
    }

    /**
     * Fetch a unique record that has <code>PK_ID = value</code>
     */
    public up.god.jooq.tables.pojos.ResHisDeposit fetchOneByPkId(String value) {
        return fetchOne(ResHisDeposit.RES_HIS_DEPOSIT.PK_ID, value);
    }

    /**
     * Fetch records that have <code>D_AMOUNT IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByDAmount(BigDecimal... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.D_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>D_DEPOSIT_TIME IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByDDepositTime(LocalDateTime... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.D_DEPOSIT_TIME, values);
    }

    /**
     * Fetch records that have <code>S_CODE IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchBySCode(String... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.S_CODE, values);
    }

    /**
     * Fetch records that have <code>S_SERIAL IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchBySSerial(String... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.S_SERIAL, values);
    }

    /**
     * Fetch records that have <code>J_CONFIG IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByJConfig(String... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.J_CONFIG, values);
    }

    /**
     * Fetch records that have <code>RLT_DEPOSIT_SOURCE IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByRltDepositSource(Long... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.RLT_DEPOSIT_SOURCE, values);
    }

    /**
     * Fetch records that have <code>RLT_DEPOSIT_TYPE IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByRltDepositType(Long... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.RLT_DEPOSIT_TYPE, values);
    }

    /**
     * Fetch records that have <code>R_CARD_ID IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByRCardId(String... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.R_CARD_ID, values);
    }

    /**
     * Fetch records that have <code>IS_FINISHED IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByIsFinished(Boolean... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.IS_FINISHED, values);
    }

    /**
     * Fetch records that have <code>IS_ACTIVE IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByIsActive(Boolean... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.IS_ACTIVE, values);
    }

    /**
     * Fetch records that have <code>Z_SIGMA IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByZSigma(String... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.Z_SIGMA, values);
    }

    /**
     * Fetch records that have <code>Z_LANGUAGE IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByZLanguage(String... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.Z_LANGUAGE, values);
    }

    /**
     * Fetch records that have <code>Z_CREATE_BY IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByZCreateBy(String... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.Z_CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>Z_CREATE_TIME IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByZCreateTime(LocalDateTime... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.Z_CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>Z_UPDATE_BY IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByZUpdateBy(String... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.Z_UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>Z_UPDATE_TIME IN (values)</code>
     */
    public List<up.god.jooq.tables.pojos.ResHisDeposit> fetchByZUpdateTime(LocalDateTime... values) {
        return fetch(ResHisDeposit.RES_HIS_DEPOSIT.Z_UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>PK_ID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByPkIdAsync(List<String> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.PK_ID,values);
    }

    /**
     * Fetch a unique record that has <code>PK_ID = value</code> asynchronously
     */
    public CompletableFuture<up.god.jooq.tables.pojos.ResHisDeposit> fetchOneByPkIdAsync(String value) {
        return FutureTool.executeBlocking(h->h.complete(fetchOneByPkId(value)),vertx());
    }

    /**
     * Fetch records that have <code>D_AMOUNT IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByDAmountAsync(List<BigDecimal> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.D_AMOUNT,values);
    }

    /**
     * Fetch records that have <code>D_DEPOSIT_TIME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByDDepositTimeAsync(List<LocalDateTime> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.D_DEPOSIT_TIME,values);
    }

    /**
     * Fetch records that have <code>S_CODE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchBySCodeAsync(List<String> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.S_CODE,values);
    }

    /**
     * Fetch records that have <code>S_SERIAL IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchBySSerialAsync(List<String> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.S_SERIAL,values);
    }

    /**
     * Fetch records that have <code>J_CONFIG IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByJConfigAsync(List<String> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.J_CONFIG,values);
    }

    /**
     * Fetch records that have <code>RLT_DEPOSIT_SOURCE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByRltDepositSourceAsync(List<Long> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.RLT_DEPOSIT_SOURCE,values);
    }

    /**
     * Fetch records that have <code>RLT_DEPOSIT_TYPE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByRltDepositTypeAsync(List<Long> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.RLT_DEPOSIT_TYPE,values);
    }

    /**
     * Fetch records that have <code>R_CARD_ID IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByRCardIdAsync(List<String> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.R_CARD_ID,values);
    }

    /**
     * Fetch records that have <code>IS_FINISHED IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByIsFinishedAsync(List<Boolean> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.IS_FINISHED,values);
    }

    /**
     * Fetch records that have <code>IS_ACTIVE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByIsActiveAsync(List<Boolean> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.IS_ACTIVE,values);
    }

    /**
     * Fetch records that have <code>Z_SIGMA IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByZSigmaAsync(List<String> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.Z_SIGMA,values);
    }

    /**
     * Fetch records that have <code>Z_LANGUAGE IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByZLanguageAsync(List<String> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.Z_LANGUAGE,values);
    }

    /**
     * Fetch records that have <code>Z_CREATE_BY IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByZCreateByAsync(List<String> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.Z_CREATE_BY,values);
    }

    /**
     * Fetch records that have <code>Z_CREATE_TIME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByZCreateTimeAsync(List<LocalDateTime> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.Z_CREATE_TIME,values);
    }

    /**
     * Fetch records that have <code>Z_UPDATE_BY IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByZUpdateByAsync(List<String> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.Z_UPDATE_BY,values);
    }

    /**
     * Fetch records that have <code>Z_UPDATE_TIME IN (values)</code> asynchronously
     */
    public CompletableFuture<List<up.god.jooq.tables.pojos.ResHisDeposit>> fetchByZUpdateTimeAsync(List<LocalDateTime> values) {
        return fetchAsync(ResHisDeposit.RES_HIS_DEPOSIT.Z_UPDATE_TIME,values);
    }

    private io.vertx.core.Vertx vertx;

    @Override
    public void setVertx(io.vertx.core.Vertx vertx) {
        this.vertx = vertx;
    }

    @Override
    public io.vertx.core.Vertx vertx() {
        return this.vertx;
    }

}
