default: io.vertx.up.media.resolver.BufferResolver
application:
  json: io.vertx.up.media.resolver.JsonResolver
  octet-stream: io.vertx.up.media.resolver.FileResolver
  x-www-form-urlencoded: io.vertx.up.media.resolver.FileResolver
multipart:
  form-data: io.vertx.up.media.resolver.FileResolver