/*
 * This file is generated by jOOQ.
*/
package up.god.jooq.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IHtlCompensation extends Serializable {

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.PK_ID</code>. uniqueId,PK_ID
     */
    public IHtlCompensation setPkId(Long value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.PK_ID</code>. uniqueId,PK_ID
     */
    public Long getPkId();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.D_PRICE</code>. 【单价】商品的单价。,price,D_PRICE
     */
    public IHtlCompensation setDPrice(BigDecimal value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.D_PRICE</code>. 【单价】商品的单价。,price,D_PRICE
     */
    public BigDecimal getDPrice();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.S_NAME</code>. name,S_NAME
     */
    public IHtlCompensation setSName(String value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.S_NAME</code>. name,S_NAME
     */
    public String getSName();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.S_CODE</code>. code,S_CODE
     */
    public IHtlCompensation setSCode(String value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.S_CODE</code>. code,S_CODE
     */
    public String getSCode();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.S_HELP_CODE</code>. helpCode,S_HELP_CODE
     */
    public IHtlCompensation setSHelpCode(String value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.S_HELP_CODE</code>. helpCode,S_HELP_CODE
     */
    public String getSHelpCode();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.S_UNIT</code>. unit,S_UNIT
     */
    public IHtlCompensation setSUnit(String value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.S_UNIT</code>. unit,S_UNIT
     */
    public String getSUnit();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.J_CONFIG</code>. config,J_CONFIG
     */
    public IHtlCompensation setJConfig(String value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.J_CONFIG</code>. config,J_CONFIG
     */
    public String getJConfig();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.R_HOTEL_ID</code>. hotelId,R_HOTEL_ID
     */
    public IHtlCompensation setRHotelId(Long value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.R_HOTEL_ID</code>. hotelId,R_HOTEL_ID
     */
    public Long getRHotelId();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.R_PAYTERM_ID</code>. REF: SYS_CATEGORY【消费项】关联消费项ID,ptermId,R_PAYTERM_ID
     */
    public IHtlCompensation setRPaytermId(String value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.R_PAYTERM_ID</code>. REF: SYS_CATEGORY【消费项】关联消费项ID,ptermId,R_PAYTERM_ID
     */
    public String getRPaytermId();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    public IHtlCompensation setIsActive(Boolean value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.IS_ACTIVE</code>. active,IS_ACTIVE
     */
    public Boolean getIsActive();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    public IHtlCompensation setZSigma(String value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.Z_SIGMA</code>. sigma,Z_SIGMA
     */
    public String getZSigma();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.Z_LANGUAGE</code>. language,Z_LANGUAGE
     */
    public IHtlCompensation setZLanguage(String value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.Z_LANGUAGE</code>. language,Z_LANGUAGE
     */
    public String getZLanguage();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.Z_CREATE_BY</code>. createBy,Z_CREATE_BY
     */
    public IHtlCompensation setZCreateBy(String value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.Z_CREATE_BY</code>. createBy,Z_CREATE_BY
     */
    public String getZCreateBy();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.Z_CREATE_TIME</code>. createTime,Z_CREATE_TIME
     */
    public IHtlCompensation setZCreateTime(LocalDateTime value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.Z_CREATE_TIME</code>. createTime,Z_CREATE_TIME
     */
    public LocalDateTime getZCreateTime();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.Z_UPDATE_BY</code>. updateBy,Z_UPDATE_BY
     */
    public IHtlCompensation setZUpdateBy(String value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.Z_UPDATE_BY</code>. updateBy,Z_UPDATE_BY
     */
    public String getZUpdateBy();

    /**
     * Setter for <code>DB_HTL.HTL_COMPENSATION.Z_UPDATE_TIME</code>. updateTime,Z_UPDATE_TIME
     */
    public IHtlCompensation setZUpdateTime(LocalDateTime value);

    /**
     * Getter for <code>DB_HTL.HTL_COMPENSATION.Z_UPDATE_TIME</code>. updateTime,Z_UPDATE_TIME
     */
    public LocalDateTime getZUpdateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IHtlCompensation
     */
    public void from(up.god.jooq.tables.interfaces.IHtlCompensation from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IHtlCompensation
     */
    public <E extends up.god.jooq.tables.interfaces.IHtlCompensation> E into(E into);

    default IHtlCompensation fromJson(io.vertx.core.json.JsonObject json) {
        setPkId(json.getLong("PK_ID"));
        // Omitting unrecognized type java.math.BigDecimal for column D_PRICE!
        setSName(json.getString("S_NAME"));
        setSCode(json.getString("S_CODE"));
        setSHelpCode(json.getString("S_HELP_CODE"));
        setSUnit(json.getString("S_UNIT"));
        setJConfig(json.getString("J_CONFIG"));
        setRHotelId(json.getLong("R_HOTEL_ID"));
        setRPaytermId(json.getString("R_PAYTERM_ID"));
        setIsActive(json.getBoolean("IS_ACTIVE"));
        setZSigma(json.getString("Z_SIGMA"));
        setZLanguage(json.getString("Z_LANGUAGE"));
        setZCreateBy(json.getString("Z_CREATE_BY"));
        // Omitting unrecognized type java.time.LocalDateTime for column Z_CREATE_TIME!
        setZUpdateBy(json.getString("Z_UPDATE_BY"));
        // Omitting unrecognized type java.time.LocalDateTime for column Z_UPDATE_TIME!
        return this;
    }


    default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("PK_ID",getPkId());
        // Omitting unrecognized type java.math.BigDecimal for column D_PRICE!
        json.put("S_NAME",getSName());
        json.put("S_CODE",getSCode());
        json.put("S_HELP_CODE",getSHelpCode());
        json.put("S_UNIT",getSUnit());
        json.put("J_CONFIG",getJConfig());
        json.put("R_HOTEL_ID",getRHotelId());
        json.put("R_PAYTERM_ID",getRPaytermId());
        json.put("IS_ACTIVE",getIsActive());
        json.put("Z_SIGMA",getZSigma());
        json.put("Z_LANGUAGE",getZLanguage());
        json.put("Z_CREATE_BY",getZCreateBy());
        // Omitting unrecognized type java.time.LocalDateTime for column Z_CREATE_TIME!
        json.put("Z_UPDATE_BY",getZUpdateBy());
        // Omitting unrecognized type java.time.LocalDateTime for column Z_UPDATE_TIME!
        return json;
    }

}
