/*
 * This file is generated by jOOQ.
*/
package up.zero.domain;


import javax.annotation.Generated;

import up.zero.domain.tables.SRole;
import up.zero.domain.tables.SUser;


/**
 * Convenience access to all tables in UP_ARES
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>UP_ARES.S_ROLE</code>.
     */
    public static final SRole S_ROLE = up.zero.domain.tables.SRole.S_ROLE;

    /**
     * The table <code>UP_ARES.S_USER</code>.
     */
    public static final SUser S_USER = up.zero.domain.tables.SUser.S_USER;
}
