/*
 * This file is generated by jOOQ.
*/
package up.zero.domain.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICiDept extends Serializable {

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.KEY</code>. 「key」- 部门ID
     */
    public ICiDept setKey(String value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.KEY</code>. 「key」- 部门ID
     */
    public String getKey();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.NAME</code>. 「name」- 部门名称
     */
    public ICiDept setName(String value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.NAME</code>. 「name」- 部门名称
     */
    public String getName();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.CODE</code>. 「code」- 部门编码
     */
    public ICiDept setCode(String value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.CODE</code>. 「code」- 部门编码
     */
    public String getCode();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.COMMENT</code>. 「comment」- 部门备注
     */
    public ICiDept setComment(String value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.COMMENT</code>. 「comment」- 部门备注
     */
    public String getComment();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.MANAGER</code>. 「manager」- 部门经理
     */
    public ICiDept setManager(String value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.MANAGER</code>. 「manager」- 部门经理
     */
    public String getManager();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.CONTACT_MOBILE</code>. 「contactMobile」- 部门联系人手机
     */
    public ICiDept setContactMobile(String value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.CONTACT_MOBILE</code>. 「contactMobile」- 部门联系人手机
     */
    public String getContactMobile();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.CONTACT_NAME</code>. 「contactName」- 部门联系人姓名
     */
    public ICiDept setContactName(String value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.CONTACT_NAME</code>. 「contactName」- 部门联系人姓名
     */
    public String getContactName();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.APP_ID</code>. 「appId」- 部门关联的APP ID
     */
    public ICiDept setAppId(String value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.APP_ID</code>. 「appId」- 部门关联的APP ID
     */
    public String getAppId();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.LANGUAGE</code>. 「language」- 使用的语言
     */
    public ICiDept setLanguage(String value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.LANGUAGE</code>. 「language」- 使用的语言
     */
    public String getLanguage();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.ACTIVE</code>. 「active」- 是否启用
     */
    public ICiDept setActive(Boolean value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.ACTIVE</code>. 「active」- 是否启用
     */
    public Boolean getActive();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.METADATA</code>. 「metadata」- 附加配置数据
     */
    public ICiDept setMetadata(String value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.METADATA</code>. 「metadata」- 附加配置数据
     */
    public String getMetadata();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    public ICiDept setCreatedAt(LocalDateTime value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    public LocalDateTime getCreatedAt();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.CREATED_BY</code>. 「createdBy」- 创建人
     */
    public ICiDept setCreatedBy(String value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.CREATED_BY</code>. 「createdBy」- 创建人
     */
    public String getCreatedBy();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    public ICiDept setUpdatedAt(LocalDateTime value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    public LocalDateTime getUpdatedAt();

    /**
     * Setter for <code>DB_RBAC.CI_DEPT.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    public ICiDept setUpdatedBy(String value);

    /**
     * Getter for <code>DB_RBAC.CI_DEPT.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    public String getUpdatedBy();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICiDept
     */
    public void from(up.zero.domain.tables.interfaces.ICiDept from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICiDept
     */
    public <E extends up.zero.domain.tables.interfaces.ICiDept> E into(E into);

    default ICiDept fromJson(io.vertx.core.json.JsonObject json) {
        setKey(json.getString("KEY"));
        setName(json.getString("NAME"));
        setCode(json.getString("CODE"));
        setComment(json.getString("COMMENT"));
        setManager(json.getString("MANAGER"));
        setContactMobile(json.getString("CONTACT_MOBILE"));
        setContactName(json.getString("CONTACT_NAME"));
        setAppId(json.getString("APP_ID"));
        setLanguage(json.getString("LANGUAGE"));
        setActive(json.getBoolean("ACTIVE"));
        setMetadata(json.getString("METADATA"));
        // Omitting unrecognized type java.time.LocalDateTime for column CREATED_AT!
        setCreatedBy(json.getString("CREATED_BY"));
        // Omitting unrecognized type java.time.LocalDateTime for column UPDATED_AT!
        setUpdatedBy(json.getString("UPDATED_BY"));
        return this;
    }


    default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("KEY",getKey());
        json.put("NAME",getName());
        json.put("CODE",getCode());
        json.put("COMMENT",getComment());
        json.put("MANAGER",getManager());
        json.put("CONTACT_MOBILE",getContactMobile());
        json.put("CONTACT_NAME",getContactName());
        json.put("APP_ID",getAppId());
        json.put("LANGUAGE",getLanguage());
        json.put("ACTIVE",getActive());
        json.put("METADATA",getMetadata());
        // Omitting unrecognized type java.time.LocalDateTime for column CREATED_AT!
        json.put("CREATED_BY",getCreatedBy());
        // Omitting unrecognized type java.time.LocalDateTime for column UPDATED_AT!
        json.put("UPDATED_BY",getUpdatedBy());
        return json;
    }

}
